// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package patientdb

import (
	"database/sql"
	"time"
)

type Family struct {
	FamilyID   int64  `json:"family_id"`
	FamilyName string `json:"family_name"`
}

type Patient struct {
	PatientID      string          `json:"patient_id"`
	Nic            string          `json:"nic"`
	FirstName      string          `json:"first_name"`
	MiddleName     string          `json:"middle_name"`
	LastName       string          `json:"last_name"`
	Dob            time.Time       `json:"dob"`
	AddressLineOne sql.NullString  `json:"address_line_one"`
	AddressLineTwo sql.NullString  `json:"address_line_two"`
	City           sql.NullString  `json:"city"`
	State          sql.NullString  `json:"state"`
	Country        string          `json:"country"`
	TellNo         string          `json:"tell_no"`
	Email          string          `json:"email"`
	Password       string          `json:"password"`
	Sex            sql.NullString  `json:"sex"`
	Height         sql.NullFloat64 `json:"height"`
	Weight         sql.NullFloat64 `json:"weight"`
	BloodGroup     sql.NullString  `json:"blood_group"`
	MaritalState   sql.NullString  `json:"marital_state"`
	Occupation     sql.NullString  `json:"occupation"`
	Nationality    sql.NullString  `json:"nationality"`
	FamilyID       sql.NullInt64   `json:"family_id"`
}
