// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: admitPatient_svc.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdmitPatientServiceClient is the client API for AdmitPatientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdmitPatientServiceClient interface {
	AdmitPatient(ctx context.Context, in *AdmitPatientParameters, opts ...grpc.CallOption) (*AddedAdmitPatientResult, error)
}

type admitPatientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdmitPatientServiceClient(cc grpc.ClientConnInterface) AdmitPatientServiceClient {
	return &admitPatientServiceClient{cc}
}

func (c *admitPatientServiceClient) AdmitPatient(ctx context.Context, in *AdmitPatientParameters, opts ...grpc.CallOption) (*AddedAdmitPatientResult, error) {
	out := new(AddedAdmitPatientResult)
	err := c.cc.Invoke(ctx, "/pb.AdmitPatientService/AdmitPatient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdmitPatientServiceServer is the server API for AdmitPatientService service.
// All implementations should embed UnimplementedAdmitPatientServiceServer
// for forward compatibility
type AdmitPatientServiceServer interface {
	AdmitPatient(context.Context, *AdmitPatientParameters) (*AddedAdmitPatientResult, error)
}

// UnimplementedAdmitPatientServiceServer should be embedded to have forward compatible implementations.
type UnimplementedAdmitPatientServiceServer struct {
}

func (UnimplementedAdmitPatientServiceServer) AdmitPatient(context.Context, *AdmitPatientParameters) (*AddedAdmitPatientResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdmitPatient not implemented")
}

// UnsafeAdmitPatientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdmitPatientServiceServer will
// result in compilation errors.
type UnsafeAdmitPatientServiceServer interface {
	mustEmbedUnimplementedAdmitPatientServiceServer()
}

func RegisterAdmitPatientServiceServer(s grpc.ServiceRegistrar, srv AdmitPatientServiceServer) {
	s.RegisterService(&AdmitPatientService_ServiceDesc, srv)
}

func _AdmitPatientService_AdmitPatient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdmitPatientParameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdmitPatientServiceServer).AdmitPatient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AdmitPatientService/AdmitPatient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdmitPatientServiceServer).AdmitPatient(ctx, req.(*AdmitPatientParameters))
	}
	return interceptor(ctx, in, info, handler)
}

// AdmitPatientService_ServiceDesc is the grpc.ServiceDesc for AdmitPatientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdmitPatientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AdmitPatientService",
	HandlerType: (*AdmitPatientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdmitPatient",
			Handler:    _AdmitPatientService_AdmitPatient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admitPatient_svc.proto",
}
