// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: center_attributes.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllCetersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllCetersRequest) Reset() {
	*x = GetAllCetersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_attributes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllCetersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCetersRequest) ProtoMessage() {}

func (x *GetAllCetersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_center_attributes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCetersRequest.ProtoReflect.Descriptor instead.
func (*GetAllCetersRequest) Descriptor() ([]byte, []int) {
	return file_center_attributes_proto_rawDescGZIP(), []int{0}
}

type Center struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CenterId     int64  `protobuf:"varint,1,opt,name=centerId,proto3" json:"centerId,omitempty"`
	CenterName   string `protobuf:"bytes,2,opt,name=centerName,proto3" json:"centerName,omitempty"`
	Address      string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	TellNo       string `protobuf:"bytes,4,opt,name=tellNo,proto3" json:"tellNo,omitempty"`
	Email        string `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	WebSite      string `protobuf:"bytes,6,opt,name=webSite,proto3" json:"webSite,omitempty"`
	ActiveStatus bool   `protobuf:"varint,7,opt,name=activeStatus,proto3" json:"activeStatus,omitempty"`
	OnlineStatus bool   `protobuf:"varint,8,opt,name=onlineStatus,proto3" json:"onlineStatus,omitempty"`
	CenterTypeId int64  `protobuf:"varint,9,opt,name=centerTypeId,proto3" json:"centerTypeId,omitempty"`
}

func (x *Center) Reset() {
	*x = Center{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_attributes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Center) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Center) ProtoMessage() {}

func (x *Center) ProtoReflect() protoreflect.Message {
	mi := &file_center_attributes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Center.ProtoReflect.Descriptor instead.
func (*Center) Descriptor() ([]byte, []int) {
	return file_center_attributes_proto_rawDescGZIP(), []int{1}
}

func (x *Center) GetCenterId() int64 {
	if x != nil {
		return x.CenterId
	}
	return 0
}

func (x *Center) GetCenterName() string {
	if x != nil {
		return x.CenterName
	}
	return ""
}

func (x *Center) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Center) GetTellNo() string {
	if x != nil {
		return x.TellNo
	}
	return ""
}

func (x *Center) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Center) GetWebSite() string {
	if x != nil {
		return x.WebSite
	}
	return ""
}

func (x *Center) GetActiveStatus() bool {
	if x != nil {
		return x.ActiveStatus
	}
	return false
}

func (x *Center) GetOnlineStatus() bool {
	if x != nil {
		return x.OnlineStatus
	}
	return false
}

func (x *Center) GetCenterTypeId() int64 {
	if x != nil {
		return x.CenterTypeId
	}
	return 0
}

type GetAllCetersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Centers []*Center `protobuf:"bytes,1,rep,name=centers,proto3" json:"centers,omitempty"`
}

func (x *GetAllCetersResponse) Reset() {
	*x = GetAllCetersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_attributes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllCetersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCetersResponse) ProtoMessage() {}

func (x *GetAllCetersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_center_attributes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCetersResponse.ProtoReflect.Descriptor instead.
func (*GetAllCetersResponse) Descriptor() ([]byte, []int) {
	return file_center_attributes_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllCetersResponse) GetCenters() []*Center {
	if x != nil {
		return x.Centers
	}
	return nil
}

var File_center_attributes_proto protoreflect.FileDescriptor

var file_center_attributes_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x15, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x92, 0x02, 0x0a, 0x06, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x6c, 0x6c, 0x4e, 0x6f, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x6c, 0x6c, 0x4e, 0x6f, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x65, 0x62, 0x53, 0x69, 0x74, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x65, 0x62, 0x53, 0x69, 0x74, 0x65, 0x12, 0x22, 0x0a,
	0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x49, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x63, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x43, 0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x24, 0x0a, 0x07, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x07,
	0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_center_attributes_proto_rawDescOnce sync.Once
	file_center_attributes_proto_rawDescData = file_center_attributes_proto_rawDesc
)

func file_center_attributes_proto_rawDescGZIP() []byte {
	file_center_attributes_proto_rawDescOnce.Do(func() {
		file_center_attributes_proto_rawDescData = protoimpl.X.CompressGZIP(file_center_attributes_proto_rawDescData)
	})
	return file_center_attributes_proto_rawDescData
}

var file_center_attributes_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_center_attributes_proto_goTypes = []interface{}{
	(*GetAllCetersRequest)(nil),  // 0: pb.GetAllCetersRequest
	(*Center)(nil),               // 1: pb.Center
	(*GetAllCetersResponse)(nil), // 2: pb.GetAllCetersResponse
}
var file_center_attributes_proto_depIdxs = []int32{
	1, // 0: pb.GetAllCetersResponse.centers:type_name -> pb.Center
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_center_attributes_proto_init() }
func file_center_attributes_proto_init() {
	if File_center_attributes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_center_attributes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllCetersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_attributes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Center); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_attributes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllCetersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_center_attributes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_center_attributes_proto_goTypes,
		DependencyIndexes: file_center_attributes_proto_depIdxs,
		MessageInfos:      file_center_attributes_proto_msgTypes,
	}.Build()
	File_center_attributes_proto = out.File
	file_center_attributes_proto_rawDesc = nil
	file_center_attributes_proto_goTypes = nil
	file_center_attributes_proto_depIdxs = nil
}
