// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: center_admin_attributes.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CenterAdmin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CenterAdminId    int64  `protobuf:"varint,1,opt,name=centerAdmin_id,json=centerAdminId,proto3" json:"centerAdmin_id,omitempty"`
	CenterId         int64  `protobuf:"varint,2,opt,name=center_id,json=centerId,proto3" json:"center_id,omitempty"`
	UserId           string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName         string `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FirstName        string `protobuf:"bytes,5,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName         string `protobuf:"bytes,6,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Nic              string `protobuf:"bytes,7,opt,name=nic,proto3" json:"nic,omitempty"`
	TellNo           string `protobuf:"bytes,8,opt,name=tell_no,json=tellNo,proto3" json:"tell_no,omitempty"`
	Address          string `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	UserEmail        string `protobuf:"bytes,10,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	UserPwd          string `protobuf:"bytes,11,opt,name=user_pwd,json=userPwd,proto3" json:"user_pwd,omitempty"`
	IsEmailVerified  bool   `protobuf:"varint,12,opt,name=is_email_verified,json=isEmailVerified,proto3" json:"is_email_verified,omitempty"`
	IsTellNoVerified bool   `protobuf:"varint,13,opt,name=is_tell_no_verified,json=isTellNoVerified,proto3" json:"is_tell_no_verified,omitempty"`
}

func (x *CenterAdmin) Reset() {
	*x = CenterAdmin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_admin_attributes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CenterAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CenterAdmin) ProtoMessage() {}

func (x *CenterAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_center_admin_attributes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CenterAdmin.ProtoReflect.Descriptor instead.
func (*CenterAdmin) Descriptor() ([]byte, []int) {
	return file_center_admin_attributes_proto_rawDescGZIP(), []int{0}
}

func (x *CenterAdmin) GetCenterAdminId() int64 {
	if x != nil {
		return x.CenterAdminId
	}
	return 0
}

func (x *CenterAdmin) GetCenterId() int64 {
	if x != nil {
		return x.CenterId
	}
	return 0
}

func (x *CenterAdmin) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CenterAdmin) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CenterAdmin) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CenterAdmin) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CenterAdmin) GetNic() string {
	if x != nil {
		return x.Nic
	}
	return ""
}

func (x *CenterAdmin) GetTellNo() string {
	if x != nil {
		return x.TellNo
	}
	return ""
}

func (x *CenterAdmin) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CenterAdmin) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *CenterAdmin) GetUserPwd() string {
	if x != nil {
		return x.UserPwd
	}
	return ""
}

func (x *CenterAdmin) GetIsEmailVerified() bool {
	if x != nil {
		return x.IsEmailVerified
	}
	return false
}

func (x *CenterAdmin) GetIsTellNoVerified() bool {
	if x != nil {
		return x.IsTellNoVerified
	}
	return false
}

type RegisterCenterAdminRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId           string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CenterId         int64  `protobuf:"varint,2,opt,name=center_id,json=centerId,proto3" json:"center_id,omitempty"`
	UserName         string `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FirstName        string `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName         string `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Nic              string `protobuf:"bytes,6,opt,name=nic,proto3" json:"nic,omitempty"`
	TellNo           string `protobuf:"bytes,7,opt,name=tell_no,json=tellNo,proto3" json:"tell_no,omitempty"`
	Address          string `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	UserEmail        string `protobuf:"bytes,9,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	UserPwd          string `protobuf:"bytes,10,opt,name=user_pwd,json=userPwd,proto3" json:"user_pwd,omitempty"`
	IsEmailVerified  bool   `protobuf:"varint,11,opt,name=is_email_verified,json=isEmailVerified,proto3" json:"is_email_verified,omitempty"`
	IsTellNoVerified bool   `protobuf:"varint,12,opt,name=is_tell_no_verified,json=isTellNoVerified,proto3" json:"is_tell_no_verified,omitempty"`
}

func (x *RegisterCenterAdminRequest) Reset() {
	*x = RegisterCenterAdminRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_admin_attributes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterCenterAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCenterAdminRequest) ProtoMessage() {}

func (x *RegisterCenterAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_center_admin_attributes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCenterAdminRequest.ProtoReflect.Descriptor instead.
func (*RegisterCenterAdminRequest) Descriptor() ([]byte, []int) {
	return file_center_admin_attributes_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterCenterAdminRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterCenterAdminRequest) GetCenterId() int64 {
	if x != nil {
		return x.CenterId
	}
	return 0
}

func (x *RegisterCenterAdminRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *RegisterCenterAdminRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterCenterAdminRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RegisterCenterAdminRequest) GetNic() string {
	if x != nil {
		return x.Nic
	}
	return ""
}

func (x *RegisterCenterAdminRequest) GetTellNo() string {
	if x != nil {
		return x.TellNo
	}
	return ""
}

func (x *RegisterCenterAdminRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterCenterAdminRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *RegisterCenterAdminRequest) GetUserPwd() string {
	if x != nil {
		return x.UserPwd
	}
	return ""
}

func (x *RegisterCenterAdminRequest) GetIsEmailVerified() bool {
	if x != nil {
		return x.IsEmailVerified
	}
	return false
}

func (x *RegisterCenterAdminRequest) GetIsTellNoVerified() bool {
	if x != nil {
		return x.IsTellNoVerified
	}
	return false
}

type RegisterCenterAdminResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CenterAdminId int64  `protobuf:"varint,1,opt,name=centerAdmin_id,json=centerAdminId,proto3" json:"centerAdmin_id,omitempty"`
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Status        int64  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *RegisterCenterAdminResponse) Reset() {
	*x = RegisterCenterAdminResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_admin_attributes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterCenterAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCenterAdminResponse) ProtoMessage() {}

func (x *RegisterCenterAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_center_admin_attributes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCenterAdminResponse.ProtoReflect.Descriptor instead.
func (*RegisterCenterAdminResponse) Descriptor() ([]byte, []int) {
	return file_center_admin_attributes_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterCenterAdminResponse) GetCenterAdminId() int64 {
	if x != nil {
		return x.CenterAdminId
	}
	return 0
}

func (x *RegisterCenterAdminResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterCenterAdminResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterCenterAdminResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetAllCenterAdminsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CenterId int64 `protobuf:"varint,1,opt,name=center_id,json=centerId,proto3" json:"center_id,omitempty"`
}

func (x *GetAllCenterAdminsRequest) Reset() {
	*x = GetAllCenterAdminsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_admin_attributes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllCenterAdminsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCenterAdminsRequest) ProtoMessage() {}

func (x *GetAllCenterAdminsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_center_admin_attributes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCenterAdminsRequest.ProtoReflect.Descriptor instead.
func (*GetAllCenterAdminsRequest) Descriptor() ([]byte, []int) {
	return file_center_admin_attributes_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllCenterAdminsRequest) GetCenterId() int64 {
	if x != nil {
		return x.CenterId
	}
	return 0
}

type GetAllCenterAdminsByNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CenterId int64  `protobuf:"varint,1,opt,name=center_id,json=centerId,proto3" json:"center_id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetAllCenterAdminsByNameRequest) Reset() {
	*x = GetAllCenterAdminsByNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_admin_attributes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllCenterAdminsByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCenterAdminsByNameRequest) ProtoMessage() {}

func (x *GetAllCenterAdminsByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_center_admin_attributes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCenterAdminsByNameRequest.ProtoReflect.Descriptor instead.
func (*GetAllCenterAdminsByNameRequest) Descriptor() ([]byte, []int) {
	return file_center_admin_attributes_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllCenterAdminsByNameRequest) GetCenterId() int64 {
	if x != nil {
		return x.CenterId
	}
	return 0
}

func (x *GetAllCenterAdminsByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetAllCenterAdminsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CenterAdmins []*CenterAdmin `protobuf:"bytes,1,rep,name=centerAdmins,proto3" json:"centerAdmins,omitempty"`
}

func (x *GetAllCenterAdminsResponse) Reset() {
	*x = GetAllCenterAdminsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_center_admin_attributes_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllCenterAdminsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCenterAdminsResponse) ProtoMessage() {}

func (x *GetAllCenterAdminsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_center_admin_attributes_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCenterAdminsResponse.ProtoReflect.Descriptor instead.
func (*GetAllCenterAdminsResponse) Descriptor() ([]byte, []int) {
	return file_center_admin_attributes_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllCenterAdminsResponse) GetCenterAdmins() []*CenterAdmin {
	if x != nil {
		return x.CenterAdmins
	}
	return nil
}

var File_center_admin_attributes_proto protoreflect.FileDescriptor

var file_center_admin_attributes_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x61,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0x9d, 0x03, 0x0a, 0x0b, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x63, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x65,
	0x6e, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69, 0x63,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x69, 0x63, 0x12, 0x17, 0x0a, 0x07, 0x74,
	0x65, 0x6c, 0x6c, 0x5f, 0x6e, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65,
	0x6c, 0x6c, 0x4e, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1d,
	0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x19, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x77, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x50, 0x77, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x69, 0x73, 0x5f, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0f, 0x69, 0x73, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x65, 0x64, 0x12, 0x2d, 0x0a, 0x13, 0x69, 0x73, 0x5f, 0x74, 0x65, 0x6c, 0x6c, 0x5f,
	0x6e, 0x6f, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x10, 0x69, 0x73, 0x54, 0x65, 0x6c, 0x6c, 0x4e, 0x6f, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x22, 0x85, 0x03, 0x0a, 0x1a, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6e, 0x69, 0x63, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x6c, 0x6c, 0x5f, 0x6e, 0x6f, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x6c, 0x6c, 0x4e, 0x6f, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x77,
	0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x50, 0x77, 0x64,
	0x12, 0x2a, 0x0a, 0x11, 0x69, 0x73, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x76, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x69, 0x73, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x2d, 0x0a, 0x13,
	0x69, 0x73, 0x5f, 0x74, 0x65, 0x6c, 0x6c, 0x5f, 0x6e, 0x6f, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x69, 0x73, 0x54, 0x65, 0x6c,
	0x6c, 0x4e, 0x6f, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x22, 0x8f, 0x01, 0x0a, 0x1b,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0d, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x38, 0x0a,
	0x19, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x65,
	0x6e, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x52, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x73, 0x42, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x65,
	0x6e, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x51, 0x0a, 0x1a, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0c, 0x63, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x52, 0x0c, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x73, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_center_admin_attributes_proto_rawDescOnce sync.Once
	file_center_admin_attributes_proto_rawDescData = file_center_admin_attributes_proto_rawDesc
)

func file_center_admin_attributes_proto_rawDescGZIP() []byte {
	file_center_admin_attributes_proto_rawDescOnce.Do(func() {
		file_center_admin_attributes_proto_rawDescData = protoimpl.X.CompressGZIP(file_center_admin_attributes_proto_rawDescData)
	})
	return file_center_admin_attributes_proto_rawDescData
}

var file_center_admin_attributes_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_center_admin_attributes_proto_goTypes = []interface{}{
	(*CenterAdmin)(nil),                     // 0: pb.CenterAdmin
	(*RegisterCenterAdminRequest)(nil),      // 1: pb.RegisterCenterAdminRequest
	(*RegisterCenterAdminResponse)(nil),     // 2: pb.RegisterCenterAdminResponse
	(*GetAllCenterAdminsRequest)(nil),       // 3: pb.GetAllCenterAdminsRequest
	(*GetAllCenterAdminsByNameRequest)(nil), // 4: pb.GetAllCenterAdminsByNameRequest
	(*GetAllCenterAdminsResponse)(nil),      // 5: pb.GetAllCenterAdminsResponse
}
var file_center_admin_attributes_proto_depIdxs = []int32{
	0, // 0: pb.GetAllCenterAdminsResponse.centerAdmins:type_name -> pb.CenterAdmin
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_center_admin_attributes_proto_init() }
func file_center_admin_attributes_proto_init() {
	if File_center_admin_attributes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_center_admin_attributes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CenterAdmin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_admin_attributes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterCenterAdminRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_admin_attributes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterCenterAdminResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_admin_attributes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllCenterAdminsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_admin_attributes_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllCenterAdminsByNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_center_admin_attributes_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllCenterAdminsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_center_admin_attributes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_center_admin_attributes_proto_goTypes,
		DependencyIndexes: file_center_admin_attributes_proto_depIdxs,
		MessageInfos:      file_center_admin_attributes_proto_msgTypes,
	}.Build()
	File_center_admin_attributes_proto = out.File
	file_center_admin_attributes_proto_rawDesc = nil
	file_center_admin_attributes_proto_goTypes = nil
	file_center_admin_attributes_proto_depIdxs = nil
}
