// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: nurseNote_attributes.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PatientIdParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PatientId string `protobuf:"bytes,1,opt,name=patientId,proto3" json:"patientId,omitempty"`
}

func (x *PatientIdParam) Reset() {
	*x = PatientIdParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nurseNote_attributes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatientIdParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientIdParam) ProtoMessage() {}

func (x *PatientIdParam) ProtoReflect() protoreflect.Message {
	mi := &file_nurseNote_attributes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientIdParam.ProtoReflect.Descriptor instead.
func (*PatientIdParam) Descriptor() ([]byte, []int) {
	return file_nurseNote_attributes_proto_rawDescGZIP(), []int{0}
}

func (x *PatientIdParam) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

type NurseNoteResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NursingNoteId  int64  `protobuf:"varint,1,opt,name=nursingNoteId,proto3" json:"nursingNoteId,omitempty"`
	Remark         string `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	NursingCare    string `protobuf:"bytes,3,opt,name=nursingCare,proto3" json:"nursingCare,omitempty"`
	NotesDateTimer string `protobuf:"bytes,4,opt,name=notesDateTimer,proto3" json:"notesDateTimer,omitempty"`
	NurseId        int64  `protobuf:"varint,5,opt,name=nurse_id,json=nurseId,proto3" json:"nurse_id,omitempty"`
	PatientId      string `protobuf:"bytes,6,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
}

func (x *NurseNoteResult) Reset() {
	*x = NurseNoteResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nurseNote_attributes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NurseNoteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NurseNoteResult) ProtoMessage() {}

func (x *NurseNoteResult) ProtoReflect() protoreflect.Message {
	mi := &file_nurseNote_attributes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NurseNoteResult.ProtoReflect.Descriptor instead.
func (*NurseNoteResult) Descriptor() ([]byte, []int) {
	return file_nurseNote_attributes_proto_rawDescGZIP(), []int{1}
}

func (x *NurseNoteResult) GetNursingNoteId() int64 {
	if x != nil {
		return x.NursingNoteId
	}
	return 0
}

func (x *NurseNoteResult) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *NurseNoteResult) GetNursingCare() string {
	if x != nil {
		return x.NursingCare
	}
	return ""
}

func (x *NurseNoteResult) GetNotesDateTimer() string {
	if x != nil {
		return x.NotesDateTimer
	}
	return ""
}

func (x *NurseNoteResult) GetNurseId() int64 {
	if x != nil {
		return x.NurseId
	}
	return 0
}

func (x *NurseNoteResult) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

type LatestNurseNoteResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Remark         string `protobuf:"bytes,1,opt,name=remark,proto3" json:"remark,omitempty"`
	NursingCare    string `protobuf:"bytes,2,opt,name=nursingCare,proto3" json:"nursingCare,omitempty"`
	NotesDateTimer string `protobuf:"bytes,3,opt,name=notesDateTimer,proto3" json:"notesDateTimer,omitempty"`
	NurseName      string `protobuf:"bytes,4,opt,name=nurseName,proto3" json:"nurseName,omitempty"`
}

func (x *LatestNurseNoteResult) Reset() {
	*x = LatestNurseNoteResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nurseNote_attributes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LatestNurseNoteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestNurseNoteResult) ProtoMessage() {}

func (x *LatestNurseNoteResult) ProtoReflect() protoreflect.Message {
	mi := &file_nurseNote_attributes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestNurseNoteResult.ProtoReflect.Descriptor instead.
func (*LatestNurseNoteResult) Descriptor() ([]byte, []int) {
	return file_nurseNote_attributes_proto_rawDescGZIP(), []int{2}
}

func (x *LatestNurseNoteResult) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *LatestNurseNoteResult) GetNursingCare() string {
	if x != nil {
		return x.NursingCare
	}
	return ""
}

func (x *LatestNurseNoteResult) GetNotesDateTimer() string {
	if x != nil {
		return x.NotesDateTimer
	}
	return ""
}

func (x *LatestNurseNoteResult) GetNurseName() string {
	if x != nil {
		return x.NurseName
	}
	return ""
}

type GetAllLatestNurseNotesResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NurseNotes []*LatestNurseNoteResult `protobuf:"bytes,1,rep,name=nurseNotes,proto3" json:"nurseNotes,omitempty"`
}

func (x *GetAllLatestNurseNotesResult) Reset() {
	*x = GetAllLatestNurseNotesResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nurseNote_attributes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllLatestNurseNotesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllLatestNurseNotesResult) ProtoMessage() {}

func (x *GetAllLatestNurseNotesResult) ProtoReflect() protoreflect.Message {
	mi := &file_nurseNote_attributes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllLatestNurseNotesResult.ProtoReflect.Descriptor instead.
func (*GetAllLatestNurseNotesResult) Descriptor() ([]byte, []int) {
	return file_nurseNote_attributes_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllLatestNurseNotesResult) GetNurseNotes() []*LatestNurseNoteResult {
	if x != nil {
		return x.NurseNotes
	}
	return nil
}

type AddedNurseNoteResults struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value   int64  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Status  int64  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AddedNurseNoteResults) Reset() {
	*x = AddedNurseNoteResults{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nurseNote_attributes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddedNurseNoteResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddedNurseNoteResults) ProtoMessage() {}

func (x *AddedNurseNoteResults) ProtoReflect() protoreflect.Message {
	mi := &file_nurseNote_attributes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddedNurseNoteResults.ProtoReflect.Descriptor instead.
func (*AddedNurseNoteResults) Descriptor() ([]byte, []int) {
	return file_nurseNote_attributes_proto_rawDescGZIP(), []int{4}
}

func (x *AddedNurseNoteResults) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *AddedNurseNoteResults) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddedNurseNoteResults) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdatedNurseNoteResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdatedNurseNoteResult) Reset() {
	*x = UpdatedNurseNoteResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nurseNote_attributes_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatedNurseNoteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatedNurseNoteResult) ProtoMessage() {}

func (x *UpdatedNurseNoteResult) ProtoReflect() protoreflect.Message {
	mi := &file_nurseNote_attributes_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatedNurseNoteResult.ProtoReflect.Descriptor instead.
func (*UpdatedNurseNoteResult) Descriptor() ([]byte, []int) {
	return file_nurseNote_attributes_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatedNurseNoteResult) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdatedNurseNoteResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddNurseNoteParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Remark         string `protobuf:"bytes,1,opt,name=remark,proto3" json:"remark,omitempty"`
	NursingCare    string `protobuf:"bytes,2,opt,name=nursingCare,proto3" json:"nursingCare,omitempty"`
	NotesDateTimer string `protobuf:"bytes,3,opt,name=notesDateTimer,proto3" json:"notesDateTimer,omitempty"`
	CreatedAt      string `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	NurseId        string `protobuf:"bytes,5,opt,name=nurse_id,json=nurseId,proto3" json:"nurse_id,omitempty"`
	PatientId      string `protobuf:"bytes,6,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
}

func (x *AddNurseNoteParameters) Reset() {
	*x = AddNurseNoteParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nurseNote_attributes_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNurseNoteParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNurseNoteParameters) ProtoMessage() {}

func (x *AddNurseNoteParameters) ProtoReflect() protoreflect.Message {
	mi := &file_nurseNote_attributes_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNurseNoteParameters.ProtoReflect.Descriptor instead.
func (*AddNurseNoteParameters) Descriptor() ([]byte, []int) {
	return file_nurseNote_attributes_proto_rawDescGZIP(), []int{6}
}

func (x *AddNurseNoteParameters) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *AddNurseNoteParameters) GetNursingCare() string {
	if x != nil {
		return x.NursingCare
	}
	return ""
}

func (x *AddNurseNoteParameters) GetNotesDateTimer() string {
	if x != nil {
		return x.NotesDateTimer
	}
	return ""
}

func (x *AddNurseNoteParameters) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AddNurseNoteParameters) GetNurseId() string {
	if x != nil {
		return x.NurseId
	}
	return ""
}

func (x *AddNurseNoteParameters) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

type GetAllNurseNotesResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NurseNotes []*NurseNoteResult `protobuf:"bytes,1,rep,name=nurseNotes,proto3" json:"nurseNotes,omitempty"`
}

func (x *GetAllNurseNotesResult) Reset() {
	*x = GetAllNurseNotesResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nurseNote_attributes_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllNurseNotesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllNurseNotesResult) ProtoMessage() {}

func (x *GetAllNurseNotesResult) ProtoReflect() protoreflect.Message {
	mi := &file_nurseNote_attributes_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllNurseNotesResult.ProtoReflect.Descriptor instead.
func (*GetAllNurseNotesResult) Descriptor() ([]byte, []int) {
	return file_nurseNote_attributes_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllNurseNotesResult) GetNurseNotes() []*NurseNoteResult {
	if x != nil {
		return x.NurseNotes
	}
	return nil
}

type UpdateNurseNoteParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NursingNoteId  int64  `protobuf:"varint,1,opt,name=nursingNoteId,proto3" json:"nursingNoteId,omitempty"`
	Remark         string `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	NursingCare    string `protobuf:"bytes,3,opt,name=nursingCare,proto3" json:"nursingCare,omitempty"`
	NotesDateTimer string `protobuf:"bytes,4,opt,name=notesDateTimer,proto3" json:"notesDateTimer,omitempty"`
	NurseId        int64  `protobuf:"varint,5,opt,name=nurse_id,json=nurseId,proto3" json:"nurse_id,omitempty"`
	PatientId      string `protobuf:"bytes,6,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
}

func (x *UpdateNurseNoteParameters) Reset() {
	*x = UpdateNurseNoteParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nurseNote_attributes_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNurseNoteParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNurseNoteParameters) ProtoMessage() {}

func (x *UpdateNurseNoteParameters) ProtoReflect() protoreflect.Message {
	mi := &file_nurseNote_attributes_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNurseNoteParameters.ProtoReflect.Descriptor instead.
func (*UpdateNurseNoteParameters) Descriptor() ([]byte, []int) {
	return file_nurseNote_attributes_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateNurseNoteParameters) GetNursingNoteId() int64 {
	if x != nil {
		return x.NursingNoteId
	}
	return 0
}

func (x *UpdateNurseNoteParameters) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *UpdateNurseNoteParameters) GetNursingCare() string {
	if x != nil {
		return x.NursingCare
	}
	return ""
}

func (x *UpdateNurseNoteParameters) GetNotesDateTimer() string {
	if x != nil {
		return x.NotesDateTimer
	}
	return ""
}

func (x *UpdateNurseNoteParameters) GetNurseId() int64 {
	if x != nil {
		return x.NurseId
	}
	return 0
}

func (x *UpdateNurseNoteParameters) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

var File_nurseNote_attributes_proto protoreflect.FileDescriptor

var file_nurseNote_attributes_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6e, 0x75, 0x72, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x5f, 0x61, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x22, 0x2e, 0x0a, 0x0e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x22, 0xd3, 0x01, 0x0a, 0x0f, 0x4e, 0x75, 0x72, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x6e, 0x75, 0x72, 0x73, 0x69, 0x6e, 0x67, 0x4e,
	0x6f, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x6e, 0x75, 0x72,
	0x73, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x6d, 0x61, 0x72, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61,
	0x72, 0x6b, 0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x75, 0x72, 0x73, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x75, 0x72, 0x73, 0x69, 0x6e, 0x67,
	0x43, 0x61, 0x72, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x44, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6e, 0x6f,
	0x74, 0x65, 0x73, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08,
	0x6e, 0x75, 0x72, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x6e, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x74, 0x69, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x74,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x97, 0x01, 0x0a, 0x15, 0x4c, 0x61, 0x74, 0x65, 0x73,
	0x74, 0x4e, 0x75, 0x72, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x75, 0x72, 0x73,
	0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e,
	0x75, 0x72, 0x73, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x6e, 0x6f,
	0x74, 0x65, 0x73, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x75, 0x72, 0x73, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x75, 0x72, 0x73, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x59, 0x0a, 0x1c, 0x67, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74,
	0x4e, 0x75, 0x72, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x39, 0x0a, 0x0a, 0x6e, 0x75, 0x72, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74,
	0x4e, 0x75, 0x72, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52,
	0x0a, 0x6e, 0x75, 0x72, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x22, 0x5f, 0x0a, 0x15, 0x41,
	0x64, 0x64, 0x65, 0x64, 0x4e, 0x75, 0x72, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4a, 0x0a, 0x16,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x4e, 0x75, 0x72, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xd2, 0x01, 0x0a, 0x16, 0x41, 0x64, 0x64,
	0x4e, 0x75, 0x72, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x20, 0x0a, 0x0b, 0x6e,
	0x75, 0x72, 0x73, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x6e, 0x75, 0x72, 0x73, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x65, 0x12, 0x26, 0x0a,
	0x0e, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x44, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x75, 0x72, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x4d, 0x0a,
	0x16, 0x67, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4e, 0x75, 0x72, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x33, 0x0a, 0x0a, 0x6e, 0x75, 0x72, 0x73, 0x65,
	0x4e, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62,
	0x2e, 0x4e, 0x75, 0x72, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x52, 0x0a, 0x6e, 0x75, 0x72, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x22, 0xdd, 0x01, 0x0a,
	0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x75, 0x72, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x65,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x6e, 0x75,
	0x72, 0x73, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0d, 0x6e, 0x75, 0x72, 0x73, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x74, 0x65, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x75, 0x72, 0x73,
	0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e,
	0x75, 0x72, 0x73, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x6e, 0x6f,
	0x74, 0x65, 0x73, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x75, 0x72, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6e, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nurseNote_attributes_proto_rawDescOnce sync.Once
	file_nurseNote_attributes_proto_rawDescData = file_nurseNote_attributes_proto_rawDesc
)

func file_nurseNote_attributes_proto_rawDescGZIP() []byte {
	file_nurseNote_attributes_proto_rawDescOnce.Do(func() {
		file_nurseNote_attributes_proto_rawDescData = protoimpl.X.CompressGZIP(file_nurseNote_attributes_proto_rawDescData)
	})
	return file_nurseNote_attributes_proto_rawDescData
}

var file_nurseNote_attributes_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_nurseNote_attributes_proto_goTypes = []interface{}{
	(*PatientIdParam)(nil),               // 0: pb.PatientIdParam
	(*NurseNoteResult)(nil),              // 1: pb.NurseNoteResult
	(*LatestNurseNoteResult)(nil),        // 2: pb.LatestNurseNoteResult
	(*GetAllLatestNurseNotesResult)(nil), // 3: pb.getAllLatestNurseNotesResult
	(*AddedNurseNoteResults)(nil),        // 4: pb.AddedNurseNoteResults
	(*UpdatedNurseNoteResult)(nil),       // 5: pb.UpdatedNurseNoteResult
	(*AddNurseNoteParameters)(nil),       // 6: pb.AddNurseNoteParameters
	(*GetAllNurseNotesResult)(nil),       // 7: pb.getAllNurseNotesResult
	(*UpdateNurseNoteParameters)(nil),    // 8: pb.UpdateNurseNoteParameters
}
var file_nurseNote_attributes_proto_depIdxs = []int32{
	2, // 0: pb.getAllLatestNurseNotesResult.nurseNotes:type_name -> pb.LatestNurseNoteResult
	1, // 1: pb.getAllNurseNotesResult.nurseNotes:type_name -> pb.NurseNoteResult
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_nurseNote_attributes_proto_init() }
func file_nurseNote_attributes_proto_init() {
	if File_nurseNote_attributes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nurseNote_attributes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatientIdParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nurseNote_attributes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NurseNoteResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nurseNote_attributes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LatestNurseNoteResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nurseNote_attributes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllLatestNurseNotesResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nurseNote_attributes_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddedNurseNoteResults); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nurseNote_attributes_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatedNurseNoteResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nurseNote_attributes_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNurseNoteParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nurseNote_attributes_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllNurseNotesResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nurseNote_attributes_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNurseNoteParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nurseNote_attributes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nurseNote_attributes_proto_goTypes,
		DependencyIndexes: file_nurseNote_attributes_proto_depIdxs,
		MessageInfos:      file_nurseNote_attributes_proto_msgTypes,
	}.Build()
	File_nurseNote_attributes_proto = out.File
	file_nurseNote_attributes_proto_rawDesc = nil
	file_nurseNote_attributes_proto_goTypes = nil
	file_nurseNote_attributes_proto_depIdxs = nil
}
