// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: observation_attributes.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddedObservationResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value   int64  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Status  int64  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AddedObservationResult) Reset() {
	*x = AddedObservationResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_observation_attributes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddedObservationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddedObservationResult) ProtoMessage() {}

func (x *AddedObservationResult) ProtoReflect() protoreflect.Message {
	mi := &file_observation_attributes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddedObservationResult.ProtoReflect.Descriptor instead.
func (*AddedObservationResult) Descriptor() ([]byte, []int) {
	return file_observation_attributes_proto_rawDescGZIP(), []int{0}
}

func (x *AddedObservationResult) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *AddedObservationResult) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddedObservationResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdatedObservationResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdatedObservationResult) Reset() {
	*x = UpdatedObservationResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_observation_attributes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatedObservationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatedObservationResult) ProtoMessage() {}

func (x *UpdatedObservationResult) ProtoReflect() protoreflect.Message {
	mi := &file_observation_attributes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatedObservationResult.ProtoReflect.Descriptor instead.
func (*UpdatedObservationResult) Descriptor() ([]byte, []int) {
	return file_observation_attributes_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatedObservationResult) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdatedObservationResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddObservationParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObservationDateTime string  `protobuf:"bytes,1,opt,name=observationDateTime,proto3" json:"observationDateTime,omitempty"`
	BpSis               float32 `protobuf:"fixed32,2,opt,name=bpSis,proto3" json:"bpSis,omitempty"`
	BpDia               float32 `protobuf:"fixed32,3,opt,name=bpDia,proto3" json:"bpDia,omitempty"`
	Pr                  float32 `protobuf:"fixed32,4,opt,name=pr,proto3" json:"pr,omitempty"`
	Rr                  float32 `protobuf:"fixed32,5,opt,name=rr,proto3" json:"rr,omitempty"`
	Temp                float32 `protobuf:"fixed32,6,opt,name=temp,proto3" json:"temp,omitempty"`
	Notes               string  `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	PatientId           string  `protobuf:"bytes,8,opt,name=patientId,proto3" json:"patientId,omitempty"`
	NurseId             int64   `protobuf:"varint,9,opt,name=nurseId,proto3" json:"nurseId,omitempty"`
}

func (x *AddObservationParameters) Reset() {
	*x = AddObservationParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_observation_attributes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddObservationParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddObservationParameters) ProtoMessage() {}

func (x *AddObservationParameters) ProtoReflect() protoreflect.Message {
	mi := &file_observation_attributes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddObservationParameters.ProtoReflect.Descriptor instead.
func (*AddObservationParameters) Descriptor() ([]byte, []int) {
	return file_observation_attributes_proto_rawDescGZIP(), []int{2}
}

func (x *AddObservationParameters) GetObservationDateTime() string {
	if x != nil {
		return x.ObservationDateTime
	}
	return ""
}

func (x *AddObservationParameters) GetBpSis() float32 {
	if x != nil {
		return x.BpSis
	}
	return 0
}

func (x *AddObservationParameters) GetBpDia() float32 {
	if x != nil {
		return x.BpDia
	}
	return 0
}

func (x *AddObservationParameters) GetPr() float32 {
	if x != nil {
		return x.Pr
	}
	return 0
}

func (x *AddObservationParameters) GetRr() float32 {
	if x != nil {
		return x.Rr
	}
	return 0
}

func (x *AddObservationParameters) GetTemp() float32 {
	if x != nil {
		return x.Temp
	}
	return 0
}

func (x *AddObservationParameters) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *AddObservationParameters) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *AddObservationParameters) GetNurseId() int64 {
	if x != nil {
		return x.NurseId
	}
	return 0
}

type UpdateObservationParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObservationId       int64   `protobuf:"varint,1,opt,name=observationId,proto3" json:"observationId,omitempty"`
	ObservationDateTime string  `protobuf:"bytes,2,opt,name=observationDateTime,proto3" json:"observationDateTime,omitempty"`
	BpSis               float32 `protobuf:"fixed32,3,opt,name=bpSis,proto3" json:"bpSis,omitempty"`
	BpDia               float32 `protobuf:"fixed32,4,opt,name=bpDia,proto3" json:"bpDia,omitempty"`
	Pr                  float32 `protobuf:"fixed32,5,opt,name=pr,proto3" json:"pr,omitempty"`
	Rr                  float32 `protobuf:"fixed32,6,opt,name=rr,proto3" json:"rr,omitempty"`
	Temp                float32 `protobuf:"fixed32,7,opt,name=temp,proto3" json:"temp,omitempty"`
	Notes               string  `protobuf:"bytes,8,opt,name=notes,proto3" json:"notes,omitempty"`
	PatientId           string  `protobuf:"bytes,9,opt,name=patientId,proto3" json:"patientId,omitempty"`
	NurseId             int64   `protobuf:"varint,10,opt,name=nurseId,proto3" json:"nurseId,omitempty"`
}

func (x *UpdateObservationParameters) Reset() {
	*x = UpdateObservationParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_observation_attributes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateObservationParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateObservationParameters) ProtoMessage() {}

func (x *UpdateObservationParameters) ProtoReflect() protoreflect.Message {
	mi := &file_observation_attributes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateObservationParameters.ProtoReflect.Descriptor instead.
func (*UpdateObservationParameters) Descriptor() ([]byte, []int) {
	return file_observation_attributes_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateObservationParameters) GetObservationId() int64 {
	if x != nil {
		return x.ObservationId
	}
	return 0
}

func (x *UpdateObservationParameters) GetObservationDateTime() string {
	if x != nil {
		return x.ObservationDateTime
	}
	return ""
}

func (x *UpdateObservationParameters) GetBpSis() float32 {
	if x != nil {
		return x.BpSis
	}
	return 0
}

func (x *UpdateObservationParameters) GetBpDia() float32 {
	if x != nil {
		return x.BpDia
	}
	return 0
}

func (x *UpdateObservationParameters) GetPr() float32 {
	if x != nil {
		return x.Pr
	}
	return 0
}

func (x *UpdateObservationParameters) GetRr() float32 {
	if x != nil {
		return x.Rr
	}
	return 0
}

func (x *UpdateObservationParameters) GetTemp() float32 {
	if x != nil {
		return x.Temp
	}
	return 0
}

func (x *UpdateObservationParameters) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *UpdateObservationParameters) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *UpdateObservationParameters) GetNurseId() int64 {
	if x != nil {
		return x.NurseId
	}
	return 0
}

type ObservationResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObservationId       int64   `protobuf:"varint,1,opt,name=observationId,proto3" json:"observationId,omitempty"`
	ObservationDateTime string  `protobuf:"bytes,2,opt,name=observationDateTime,proto3" json:"observationDateTime,omitempty"`
	BpSis               float32 `protobuf:"fixed32,3,opt,name=bpSis,proto3" json:"bpSis,omitempty"`
	BpDia               float32 `protobuf:"fixed32,4,opt,name=bpDia,proto3" json:"bpDia,omitempty"`
	Pr                  float32 `protobuf:"fixed32,5,opt,name=pr,proto3" json:"pr,omitempty"`
	Rr                  float32 `protobuf:"fixed32,6,opt,name=rr,proto3" json:"rr,omitempty"`
	Temp                float32 `protobuf:"fixed32,7,opt,name=temp,proto3" json:"temp,omitempty"`
	Notes               string  `protobuf:"bytes,8,opt,name=notes,proto3" json:"notes,omitempty"`
	PatientId           string  `protobuf:"bytes,9,opt,name=patientId,proto3" json:"patientId,omitempty"`
	NurseId             int64   `protobuf:"varint,10,opt,name=nurseId,proto3" json:"nurseId,omitempty"`
}

func (x *ObservationResult) Reset() {
	*x = ObservationResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_observation_attributes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObservationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservationResult) ProtoMessage() {}

func (x *ObservationResult) ProtoReflect() protoreflect.Message {
	mi := &file_observation_attributes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservationResult.ProtoReflect.Descriptor instead.
func (*ObservationResult) Descriptor() ([]byte, []int) {
	return file_observation_attributes_proto_rawDescGZIP(), []int{4}
}

func (x *ObservationResult) GetObservationId() int64 {
	if x != nil {
		return x.ObservationId
	}
	return 0
}

func (x *ObservationResult) GetObservationDateTime() string {
	if x != nil {
		return x.ObservationDateTime
	}
	return ""
}

func (x *ObservationResult) GetBpSis() float32 {
	if x != nil {
		return x.BpSis
	}
	return 0
}

func (x *ObservationResult) GetBpDia() float32 {
	if x != nil {
		return x.BpDia
	}
	return 0
}

func (x *ObservationResult) GetPr() float32 {
	if x != nil {
		return x.Pr
	}
	return 0
}

func (x *ObservationResult) GetRr() float32 {
	if x != nil {
		return x.Rr
	}
	return 0
}

func (x *ObservationResult) GetTemp() float32 {
	if x != nil {
		return x.Temp
	}
	return 0
}

func (x *ObservationResult) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *ObservationResult) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *ObservationResult) GetNurseId() int64 {
	if x != nil {
		return x.NurseId
	}
	return 0
}

type GetObservationById struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObseravationId int64 `protobuf:"varint,1,opt,name=obseravationId,proto3" json:"obseravationId,omitempty"`
}

func (x *GetObservationById) Reset() {
	*x = GetObservationById{}
	if protoimpl.UnsafeEnabled {
		mi := &file_observation_attributes_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetObservationById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObservationById) ProtoMessage() {}

func (x *GetObservationById) ProtoReflect() protoreflect.Message {
	mi := &file_observation_attributes_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObservationById.ProtoReflect.Descriptor instead.
func (*GetObservationById) Descriptor() ([]byte, []int) {
	return file_observation_attributes_proto_rawDescGZIP(), []int{5}
}

func (x *GetObservationById) GetObseravationId() int64 {
	if x != nil {
		return x.ObseravationId
	}
	return 0
}

type Parameterless struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Parameterless) Reset() {
	*x = Parameterless{}
	if protoimpl.UnsafeEnabled {
		mi := &file_observation_attributes_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Parameterless) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameterless) ProtoMessage() {}

func (x *Parameterless) ProtoReflect() protoreflect.Message {
	mi := &file_observation_attributes_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameterless.ProtoReflect.Descriptor instead.
func (*Parameterless) Descriptor() ([]byte, []int) {
	return file_observation_attributes_proto_rawDescGZIP(), []int{6}
}

type PatientIdParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PatientId string `protobuf:"bytes,1,opt,name=patientId,proto3" json:"patientId,omitempty"`
}

func (x *PatientIdParameter) Reset() {
	*x = PatientIdParameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_observation_attributes_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatientIdParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientIdParameter) ProtoMessage() {}

func (x *PatientIdParameter) ProtoReflect() protoreflect.Message {
	mi := &file_observation_attributes_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientIdParameter.ProtoReflect.Descriptor instead.
func (*PatientIdParameter) Descriptor() ([]byte, []int) {
	return file_observation_attributes_proto_rawDescGZIP(), []int{7}
}

func (x *PatientIdParameter) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

type GetAllObservationsResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Observations []*ObservationResult `protobuf:"bytes,1,rep,name=observations,proto3" json:"observations,omitempty"`
}

func (x *GetAllObservationsResult) Reset() {
	*x = GetAllObservationsResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_observation_attributes_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllObservationsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllObservationsResult) ProtoMessage() {}

func (x *GetAllObservationsResult) ProtoReflect() protoreflect.Message {
	mi := &file_observation_attributes_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllObservationsResult.ProtoReflect.Descriptor instead.
func (*GetAllObservationsResult) Descriptor() ([]byte, []int) {
	return file_observation_attributes_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllObservationsResult) GetObservations() []*ObservationResult {
	if x != nil {
		return x.Observations
	}
	return nil
}

type GetAllBPResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BpValues []float32 `protobuf:"fixed32,1,rep,packed,name=bpValues,proto3" json:"bpValues,omitempty"`
}

func (x *GetAllBPResult) Reset() {
	*x = GetAllBPResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_observation_attributes_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllBPResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBPResult) ProtoMessage() {}

func (x *GetAllBPResult) ProtoReflect() protoreflect.Message {
	mi := &file_observation_attributes_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBPResult.ProtoReflect.Descriptor instead.
func (*GetAllBPResult) Descriptor() ([]byte, []int) {
	return file_observation_attributes_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllBPResult) GetBpValues() []float32 {
	if x != nil {
		return x.BpValues
	}
	return nil
}

type GetAllPRResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrValues []float32 `protobuf:"fixed32,1,rep,packed,name=prValues,proto3" json:"prValues,omitempty"`
}

func (x *GetAllPRResult) Reset() {
	*x = GetAllPRResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_observation_attributes_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllPRResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPRResult) ProtoMessage() {}

func (x *GetAllPRResult) ProtoReflect() protoreflect.Message {
	mi := &file_observation_attributes_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPRResult.ProtoReflect.Descriptor instead.
func (*GetAllPRResult) Descriptor() ([]byte, []int) {
	return file_observation_attributes_proto_rawDescGZIP(), []int{10}
}

func (x *GetAllPRResult) GetPrValues() []float32 {
	if x != nil {
		return x.PrValues
	}
	return nil
}

type GetAllRRResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rrvalues []float32 `protobuf:"fixed32,1,rep,packed,name=rrvalues,proto3" json:"rrvalues,omitempty"`
}

func (x *GetAllRRResult) Reset() {
	*x = GetAllRRResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_observation_attributes_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRRResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRRResult) ProtoMessage() {}

func (x *GetAllRRResult) ProtoReflect() protoreflect.Message {
	mi := &file_observation_attributes_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRRResult.ProtoReflect.Descriptor instead.
func (*GetAllRRResult) Descriptor() ([]byte, []int) {
	return file_observation_attributes_proto_rawDescGZIP(), []int{11}
}

func (x *GetAllRRResult) GetRrvalues() []float32 {
	if x != nil {
		return x.Rrvalues
	}
	return nil
}

type GetAllTempResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TempValues []float32 `protobuf:"fixed32,1,rep,packed,name=tempValues,proto3" json:"tempValues,omitempty"`
}

func (x *GetAllTempResult) Reset() {
	*x = GetAllTempResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_observation_attributes_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllTempResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTempResult) ProtoMessage() {}

func (x *GetAllTempResult) ProtoReflect() protoreflect.Message {
	mi := &file_observation_attributes_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTempResult.ProtoReflect.Descriptor instead.
func (*GetAllTempResult) Descriptor() ([]byte, []int) {
	return file_observation_attributes_proto_rawDescGZIP(), []int{12}
}

func (x *GetAllTempResult) GetTempValues() []float32 {
	if x != nil {
		return x.TempValues
	}
	return nil
}

var File_observation_attributes_proto protoreflect.FileDescriptor

var file_observation_attributes_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x60, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x65, 0x64, 0x4f, 0x62, 0x73, 0x65, 0x72,
	0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x4c, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x4f,
	0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0xfa, 0x01, 0x0a, 0x18, 0x41, 0x64, 0x64, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12,
	0x30, 0x0a, 0x13, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x6f, 0x62,
	0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x70, 0x53, 0x69, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x05, 0x62, 0x70, 0x53, 0x69, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x70, 0x44, 0x69, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x62, 0x70, 0x44, 0x69, 0x61, 0x12, 0x0e, 0x0a,
	0x02, 0x70, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x70, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x72, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x72, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x65, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x74, 0x65, 0x6d,
	0x70, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x74, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x74, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6e, 0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x22,
	0xa3, 0x02, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12,
	0x24, 0x0a, 0x0d, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x13, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x13, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x70, 0x53, 0x69, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x62, 0x70, 0x53, 0x69, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x62, 0x70, 0x44, 0x69, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x62, 0x70,
	0x44, 0x69, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x02, 0x70, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x72, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x02, 0x72, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x6d, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x04, 0x74, 0x65, 0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6e,
	0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6e, 0x75,
	0x72, 0x73, 0x65, 0x49, 0x64, 0x22, 0x99, 0x02, 0x0a, 0x11, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x6f,
	0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0d, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x30, 0x0a, 0x13, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13,
	0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x70, 0x53, 0x69, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x05, 0x62, 0x70, 0x53, 0x69, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x70, 0x44,
	0x69, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x62, 0x70, 0x44, 0x69, 0x61, 0x12,
	0x0e, 0x0a, 0x02, 0x70, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x70, 0x72, 0x12,
	0x0e, 0x0a, 0x02, 0x72, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x72, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x65, 0x6d, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x74,
	0x65, 0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x74,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61,
	0x74, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x75, 0x72, 0x73, 0x65,
	0x49, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6e, 0x75, 0x72, 0x73, 0x65, 0x49,
	0x64, 0x22, 0x3c, 0x0a, 0x12, 0x67, 0x65, 0x74, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x6f, 0x62, 0x73, 0x65, 0x72,
	0x61, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0e, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x61, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22,
	0x0f, 0x0a, 0x0d, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x6c, 0x65, 0x73, 0x73,
	0x22, 0x32, 0x0a, 0x12, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x74, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x22, 0x55, 0x0a, 0x18, 0x67, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4f, 0x62,
	0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x39, 0x0a, 0x0c, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x62, 0x73, 0x65,
	0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0c, 0x6f,
	0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x2c, 0x0a, 0x0e, 0x67,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x50, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x62, 0x70, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52,
	0x08, 0x62, 0x70, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x2c, 0x0a, 0x0e, 0x67, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x50, 0x52, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52, 0x08, 0x70,
	0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x2c, 0x0a, 0x0e, 0x67, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x52, 0x52, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x72, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52, 0x08, 0x72, 0x72, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x32, 0x0a, 0x10, 0x67, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54,
	0x65, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6d,
	0x70, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52, 0x0a, 0x74,
	0x65, 0x6d, 0x70, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_observation_attributes_proto_rawDescOnce sync.Once
	file_observation_attributes_proto_rawDescData = file_observation_attributes_proto_rawDesc
)

func file_observation_attributes_proto_rawDescGZIP() []byte {
	file_observation_attributes_proto_rawDescOnce.Do(func() {
		file_observation_attributes_proto_rawDescData = protoimpl.X.CompressGZIP(file_observation_attributes_proto_rawDescData)
	})
	return file_observation_attributes_proto_rawDescData
}

var file_observation_attributes_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_observation_attributes_proto_goTypes = []interface{}{
	(*AddedObservationResult)(nil),      // 0: pb.AddedObservationResult
	(*UpdatedObservationResult)(nil),    // 1: pb.UpdatedObservationResult
	(*AddObservationParameters)(nil),    // 2: pb.AddObservationParameters
	(*UpdateObservationParameters)(nil), // 3: pb.UpdateObservationParameters
	(*ObservationResult)(nil),           // 4: pb.ObservationResult
	(*GetObservationById)(nil),          // 5: pb.getObservationById
	(*Parameterless)(nil),               // 6: pb.parameterless
	(*PatientIdParameter)(nil),          // 7: pb.PatientIdParameter
	(*GetAllObservationsResult)(nil),    // 8: pb.getAllObservationsResult
	(*GetAllBPResult)(nil),              // 9: pb.getAllBPResult
	(*GetAllPRResult)(nil),              // 10: pb.getAllPRResult
	(*GetAllRRResult)(nil),              // 11: pb.getAllRRResult
	(*GetAllTempResult)(nil),            // 12: pb.getAllTempResult
}
var file_observation_attributes_proto_depIdxs = []int32{
	4, // 0: pb.getAllObservationsResult.observations:type_name -> pb.ObservationResult
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_observation_attributes_proto_init() }
func file_observation_attributes_proto_init() {
	if File_observation_attributes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_observation_attributes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddedObservationResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_observation_attributes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatedObservationResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_observation_attributes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddObservationParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_observation_attributes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateObservationParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_observation_attributes_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObservationResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_observation_attributes_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetObservationById); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_observation_attributes_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Parameterless); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_observation_attributes_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatientIdParameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_observation_attributes_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllObservationsResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_observation_attributes_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllBPResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_observation_attributes_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllPRResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_observation_attributes_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllRRResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_observation_attributes_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllTempResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_observation_attributes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_observation_attributes_proto_goTypes,
		DependencyIndexes: file_observation_attributes_proto_depIdxs,
		MessageInfos:      file_observation_attributes_proto_msgTypes,
	}.Build()
	File_observation_attributes_proto = out.File
	file_observation_attributes_proto_rawDesc = nil
	file_observation_attributes_proto_goTypes = nil
	file_observation_attributes_proto_depIdxs = nil
}
