// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: patient_attributes.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddedPatientResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *AddedPatientResult) Reset() {
	*x = AddedPatientResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_patient_attributes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddedPatientResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddedPatientResult) ProtoMessage() {}

func (x *AddedPatientResult) ProtoReflect() protoreflect.Message {
	mi := &file_patient_attributes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddedPatientResult.ProtoReflect.Descriptor instead.
func (*AddedPatientResult) Descriptor() ([]byte, []int) {
	return file_patient_attributes_proto_rawDescGZIP(), []int{0}
}

func (x *AddedPatientResult) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AddPatientParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName  string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Nic       string `protobuf:"bytes,2,opt,name=nic,proto3" json:"nic,omitempty"`
	TellNo    string `protobuf:"bytes,3,opt,name=tellNo,proto3" json:"tellNo,omitempty"`
	Address   string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	UserEmail string `protobuf:"bytes,5,opt,name=userEmail,proto3" json:"userEmail,omitempty"`
	UserPwd   string `protobuf:"bytes,6,opt,name=userPwd,proto3" json:"userPwd,omitempty"`
	CreatedAt string `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (x *AddPatientParameters) Reset() {
	*x = AddPatientParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_patient_attributes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPatientParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPatientParameters) ProtoMessage() {}

func (x *AddPatientParameters) ProtoReflect() protoreflect.Message {
	mi := &file_patient_attributes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPatientParameters.ProtoReflect.Descriptor instead.
func (*AddPatientParameters) Descriptor() ([]byte, []int) {
	return file_patient_attributes_proto_rawDescGZIP(), []int{1}
}

func (x *AddPatientParameters) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AddPatientParameters) GetNic() string {
	if x != nil {
		return x.Nic
	}
	return ""
}

func (x *AddPatientParameters) GetTellNo() string {
	if x != nil {
		return x.TellNo
	}
	return ""
}

func (x *AddPatientParameters) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddPatientParameters) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *AddPatientParameters) GetUserPwd() string {
	if x != nil {
		return x.UserPwd
	}
	return ""
}

func (x *AddPatientParameters) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type UpdatePatientParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName  string `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	Nic       string `protobuf:"bytes,3,opt,name=nic,proto3" json:"nic,omitempty"`
	TellNo    string `protobuf:"bytes,4,opt,name=tellNo,proto3" json:"tellNo,omitempty"`
	Address   string `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	UserEmail string `protobuf:"bytes,6,opt,name=userEmail,proto3" json:"userEmail,omitempty"`
	UserPwd   string `protobuf:"bytes,7,opt,name=userPwd,proto3" json:"userPwd,omitempty"`
	CreatedAt string `protobuf:"bytes,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (x *UpdatePatientParameters) Reset() {
	*x = UpdatePatientParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_patient_attributes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePatientParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePatientParameters) ProtoMessage() {}

func (x *UpdatePatientParameters) ProtoReflect() protoreflect.Message {
	mi := &file_patient_attributes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePatientParameters.ProtoReflect.Descriptor instead.
func (*UpdatePatientParameters) Descriptor() ([]byte, []int) {
	return file_patient_attributes_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePatientParameters) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePatientParameters) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UpdatePatientParameters) GetNic() string {
	if x != nil {
		return x.Nic
	}
	return ""
}

func (x *UpdatePatientParameters) GetTellNo() string {
	if x != nil {
		return x.TellNo
	}
	return ""
}

func (x *UpdatePatientParameters) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdatePatientParameters) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *UpdatePatientParameters) GetUserPwd() string {
	if x != nil {
		return x.UserPwd
	}
	return ""
}

func (x *UpdatePatientParameters) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type PatientResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PatientId      string  `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	Nic            string  `protobuf:"bytes,2,opt,name=nic,proto3" json:"nic,omitempty"`
	FirstName      string  `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	MiddleName     string  `protobuf:"bytes,4,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	LastName       string  `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Dob            string  `protobuf:"bytes,6,opt,name=dob,proto3" json:"dob,omitempty"`
	AddressLineOne string  `protobuf:"bytes,7,opt,name=address_line_one,json=addressLineOne,proto3" json:"address_line_one,omitempty"`
	AddressLineTwo string  `protobuf:"bytes,8,opt,name=address_line_two,json=addressLineTwo,proto3" json:"address_line_two,omitempty"`
	City           string  `protobuf:"bytes,9,opt,name=city,proto3" json:"city,omitempty"`
	State          string  `protobuf:"bytes,10,opt,name=state,proto3" json:"state,omitempty"`
	Country        string  `protobuf:"bytes,11,opt,name=country,proto3" json:"country,omitempty"`
	TellNo         string  `protobuf:"bytes,12,opt,name=tell_no,json=tellNo,proto3" json:"tell_no,omitempty"`
	Email          string  `protobuf:"bytes,13,opt,name=email,proto3" json:"email,omitempty"`
	Password       string  `protobuf:"bytes,14,opt,name=password,proto3" json:"password,omitempty"`
	Sex            string  `protobuf:"bytes,15,opt,name=sex,proto3" json:"sex,omitempty"`
	Height         float32 `protobuf:"fixed32,16,opt,name=height,proto3" json:"height,omitempty"`
	Weight         float32 `protobuf:"fixed32,17,opt,name=weight,proto3" json:"weight,omitempty"`
	BloodGroup     string  `protobuf:"bytes,18,opt,name=blood_group,json=bloodGroup,proto3" json:"blood_group,omitempty"`
	MaritalState   string  `protobuf:"bytes,19,opt,name=marital_state,json=maritalState,proto3" json:"marital_state,omitempty"`
	Occupation     string  `protobuf:"bytes,20,opt,name=occupation,proto3" json:"occupation,omitempty"`
	Nationality    string  `protobuf:"bytes,21,opt,name=nationality,proto3" json:"nationality,omitempty"`
	FamilyId       int64   `protobuf:"varint,22,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
}

func (x *PatientResult) Reset() {
	*x = PatientResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_patient_attributes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatientResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientResult) ProtoMessage() {}

func (x *PatientResult) ProtoReflect() protoreflect.Message {
	mi := &file_patient_attributes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientResult.ProtoReflect.Descriptor instead.
func (*PatientResult) Descriptor() ([]byte, []int) {
	return file_patient_attributes_proto_rawDescGZIP(), []int{3}
}

func (x *PatientResult) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *PatientResult) GetNic() string {
	if x != nil {
		return x.Nic
	}
	return ""
}

func (x *PatientResult) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *PatientResult) GetMiddleName() string {
	if x != nil {
		return x.MiddleName
	}
	return ""
}

func (x *PatientResult) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *PatientResult) GetDob() string {
	if x != nil {
		return x.Dob
	}
	return ""
}

func (x *PatientResult) GetAddressLineOne() string {
	if x != nil {
		return x.AddressLineOne
	}
	return ""
}

func (x *PatientResult) GetAddressLineTwo() string {
	if x != nil {
		return x.AddressLineTwo
	}
	return ""
}

func (x *PatientResult) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *PatientResult) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PatientResult) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *PatientResult) GetTellNo() string {
	if x != nil {
		return x.TellNo
	}
	return ""
}

func (x *PatientResult) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PatientResult) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *PatientResult) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *PatientResult) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *PatientResult) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *PatientResult) GetBloodGroup() string {
	if x != nil {
		return x.BloodGroup
	}
	return ""
}

func (x *PatientResult) GetMaritalState() string {
	if x != nil {
		return x.MaritalState
	}
	return ""
}

func (x *PatientResult) GetOccupation() string {
	if x != nil {
		return x.Occupation
	}
	return ""
}

func (x *PatientResult) GetNationality() string {
	if x != nil {
		return x.Nationality
	}
	return ""
}

func (x *PatientResult) GetFamilyId() int64 {
	if x != nil {
		return x.FamilyId
	}
	return 0
}

type PatientListResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Patients []*PatientResult `protobuf:"bytes,1,rep,name=patients,proto3" json:"patients,omitempty"`
}

func (x *PatientListResult) Reset() {
	*x = PatientListResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_patient_attributes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatientListResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientListResult) ProtoMessage() {}

func (x *PatientListResult) ProtoReflect() protoreflect.Message {
	mi := &file_patient_attributes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientListResult.ProtoReflect.Descriptor instead.
func (*PatientListResult) Descriptor() ([]byte, []int) {
	return file_patient_attributes_proto_rawDescGZIP(), []int{4}
}

func (x *PatientListResult) GetPatients() []*PatientResult {
	if x != nil {
		return x.Patients
	}
	return nil
}

type GetPatientsByNICParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nic string `protobuf:"bytes,1,opt,name=nic,proto3" json:"nic,omitempty"`
}

func (x *GetPatientsByNICParameters) Reset() {
	*x = GetPatientsByNICParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_patient_attributes_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPatientsByNICParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientsByNICParameters) ProtoMessage() {}

func (x *GetPatientsByNICParameters) ProtoReflect() protoreflect.Message {
	mi := &file_patient_attributes_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientsByNICParameters.ProtoReflect.Descriptor instead.
func (*GetPatientsByNICParameters) Descriptor() ([]byte, []int) {
	return file_patient_attributes_proto_rawDescGZIP(), []int{5}
}

func (x *GetPatientsByNICParameters) GetNic() string {
	if x != nil {
		return x.Nic
	}
	return ""
}

type GetPatientsByNameParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetPatientsByNameParameters) Reset() {
	*x = GetPatientsByNameParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_patient_attributes_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPatientsByNameParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientsByNameParameters) ProtoMessage() {}

func (x *GetPatientsByNameParameters) ProtoReflect() protoreflect.Message {
	mi := &file_patient_attributes_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientsByNameParameters.ProtoReflect.Descriptor instead.
func (*GetPatientsByNameParameters) Descriptor() ([]byte, []int) {
	return file_patient_attributes_proto_rawDescGZIP(), []int{6}
}

func (x *GetPatientsByNameParameters) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPatientsByTellNoParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TellNo string `protobuf:"bytes,1,opt,name=tellNo,proto3" json:"tellNo,omitempty"`
}

func (x *GetPatientsByTellNoParameters) Reset() {
	*x = GetPatientsByTellNoParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_patient_attributes_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPatientsByTellNoParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientsByTellNoParameters) ProtoMessage() {}

func (x *GetPatientsByTellNoParameters) ProtoReflect() protoreflect.Message {
	mi := &file_patient_attributes_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientsByTellNoParameters.ProtoReflect.Descriptor instead.
func (*GetPatientsByTellNoParameters) Descriptor() ([]byte, []int) {
	return file_patient_attributes_proto_rawDescGZIP(), []int{7}
}

func (x *GetPatientsByTellNoParameters) GetTellNo() string {
	if x != nil {
		return x.TellNo
	}
	return ""
}

type GetPatientsByIDParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PatientId string `protobuf:"bytes,1,opt,name=patientId,proto3" json:"patientId,omitempty"`
}

func (x *GetPatientsByIDParameters) Reset() {
	*x = GetPatientsByIDParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_patient_attributes_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPatientsByIDParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientsByIDParameters) ProtoMessage() {}

func (x *GetPatientsByIDParameters) ProtoReflect() protoreflect.Message {
	mi := &file_patient_attributes_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientsByIDParameters.ProtoReflect.Descriptor instead.
func (*GetPatientsByIDParameters) Descriptor() ([]byte, []int) {
	return file_patient_attributes_proto_rawDescGZIP(), []int{8}
}

func (x *GetPatientsByIDParameters) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

type GetPatientsParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPatientsParameters) Reset() {
	*x = GetPatientsParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_patient_attributes_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPatientsParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientsParameters) ProtoMessage() {}

func (x *GetPatientsParameters) ProtoReflect() protoreflect.Message {
	mi := &file_patient_attributes_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientsParameters.ProtoReflect.Descriptor instead.
func (*GetPatientsParameters) Descriptor() ([]byte, []int) {
	return file_patient_attributes_proto_rawDescGZIP(), []int{9}
}

var File_patient_attributes_proto protoreflect.FileDescriptor

var file_patient_attributes_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x2a,
	0x0a, 0x12, 0x41, 0x64, 0x64, 0x65, 0x64, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xcc, 0x01, 0x0a, 0x14, 0x41,
	0x64, 0x64, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6e, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x69,
	0x63, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x6c, 0x6c, 0x4e, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x65, 0x6c, 0x6c, 0x4e, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x50, 0x77, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x50, 0x77, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xe7, 0x01, 0x0a, 0x17, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69, 0x63,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x65, 0x6c, 0x6c, 0x4e, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x6c,
	0x6c, 0x4e, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x75, 0x73, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x50, 0x77, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x50, 0x77, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x22, 0xf9, 0x04, 0x0a, 0x0d, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x74, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6e, 0x69, 0x63, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x69, 0x64, 0x64,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x6f, 0x62, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x64, 0x6f, 0x62, 0x12, 0x28, 0x0a, 0x10, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x6f, 0x6e, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x6e, 0x65, 0x4f, 0x6e, 0x65, 0x12,
	0x28, 0x0a, 0x10, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x5f,
	0x74, 0x77, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x4c, 0x69, 0x6e, 0x65, 0x54, 0x77, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74,
	0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x17, 0x0a,
	0x07, 0x74, 0x65, 0x6c, 0x6c, 0x5f, 0x6e, 0x6f, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x74, 0x65, 0x6c, 0x6c, 0x4e, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18,
	0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x10, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x11, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x6c,
	0x6f, 0x6f, 0x64, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x12, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x62, 0x6c, 0x6f, 0x6f, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x23, 0x0a, 0x0d, 0x6d,
	0x61, 0x72, 0x69, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x13, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61, 0x72, 0x69, 0x74, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x63, 0x63, 0x75, 0x70, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x14,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x63, 0x63, 0x75, 0x70, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x18,
	0x15, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x69,
	0x74, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x5f, 0x69, 0x64, 0x18,
	0x16, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x49, 0x64, 0x22,
	0x42, 0x0a, 0x11, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x74, 0x69,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x08, 0x70, 0x61, 0x74, 0x69, 0x65,
	0x6e, 0x74, 0x73, 0x22, 0x2e, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e,
	0x74, 0x73, 0x42, 0x79, 0x4e, 0x49, 0x43, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6e, 0x69, 0x63, 0x22, 0x31, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e,
	0x74, 0x73, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x37, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x50, 0x61, 0x74,
	0x69, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x79, 0x54, 0x65, 0x6c, 0x6c, 0x4e, 0x6f, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x6c, 0x6c, 0x4e,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x6c, 0x6c, 0x4e, 0x6f, 0x22,
	0x39, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x79,
	0x49, 0x44, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_patient_attributes_proto_rawDescOnce sync.Once
	file_patient_attributes_proto_rawDescData = file_patient_attributes_proto_rawDesc
)

func file_patient_attributes_proto_rawDescGZIP() []byte {
	file_patient_attributes_proto_rawDescOnce.Do(func() {
		file_patient_attributes_proto_rawDescData = protoimpl.X.CompressGZIP(file_patient_attributes_proto_rawDescData)
	})
	return file_patient_attributes_proto_rawDescData
}

var file_patient_attributes_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_patient_attributes_proto_goTypes = []interface{}{
	(*AddedPatientResult)(nil),            // 0: pb.AddedPatientResult
	(*AddPatientParameters)(nil),          // 1: pb.AddPatientParameters
	(*UpdatePatientParameters)(nil),       // 2: pb.UpdatePatientParameters
	(*PatientResult)(nil),                 // 3: pb.PatientResult
	(*PatientListResult)(nil),             // 4: pb.patientListResult
	(*GetPatientsByNICParameters)(nil),    // 5: pb.GetPatientsByNICParameters
	(*GetPatientsByNameParameters)(nil),   // 6: pb.GetPatientsByNameParameters
	(*GetPatientsByTellNoParameters)(nil), // 7: pb.GetPatientsByTellNoParameters
	(*GetPatientsByIDParameters)(nil),     // 8: pb.GetPatientsByIDParameters
	(*GetPatientsParameters)(nil),         // 9: pb.GetPatientsParameters
}
var file_patient_attributes_proto_depIdxs = []int32{
	3, // 0: pb.patientListResult.patients:type_name -> pb.PatientResult
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_patient_attributes_proto_init() }
func file_patient_attributes_proto_init() {
	if File_patient_attributes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_patient_attributes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddedPatientResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_patient_attributes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPatientParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_patient_attributes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePatientParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_patient_attributes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatientResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_patient_attributes_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatientListResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_patient_attributes_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPatientsByNICParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_patient_attributes_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPatientsByNameParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_patient_attributes_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPatientsByTellNoParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_patient_attributes_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPatientsByIDParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_patient_attributes_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPatientsParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_patient_attributes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_patient_attributes_proto_goTypes,
		DependencyIndexes: file_patient_attributes_proto_depIdxs,
		MessageInfos:      file_patient_attributes_proto_msgTypes,
	}.Build()
	File_patient_attributes_proto = out.File
	file_patient_attributes_proto_rawDesc = nil
	file_patient_attributes_proto_goTypes = nil
	file_patient_attributes_proto_depIdxs = nil
}
