// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: prescription_attributes.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLatestPrescriptionsParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PatientId string `protobuf:"bytes,1,opt,name=patientId,proto3" json:"patientId,omitempty"`
}

func (x *GetLatestPrescriptionsParameters) Reset() {
	*x = GetLatestPrescriptionsParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prescription_attributes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLatestPrescriptionsParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestPrescriptionsParameters) ProtoMessage() {}

func (x *GetLatestPrescriptionsParameters) ProtoReflect() protoreflect.Message {
	mi := &file_prescription_attributes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestPrescriptionsParameters.ProtoReflect.Descriptor instead.
func (*GetLatestPrescriptionsParameters) Descriptor() ([]byte, []int) {
	return file_prescription_attributes_proto_rawDescGZIP(), []int{0}
}

func (x *GetLatestPrescriptionsParameters) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

type PrescriptionResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrescriptionId int64  `protobuf:"varint,1,opt,name=prescription_id,json=prescriptionId,proto3" json:"prescription_id,omitempty"`
	PresDate       string `protobuf:"bytes,2,opt,name=pres_date,json=presDate,proto3" json:"pres_date,omitempty"`
	PresTime       string `protobuf:"bytes,3,opt,name=pres_time,json=presTime,proto3" json:"pres_time,omitempty"`
	ActiveStatus   bool   `protobuf:"varint,4,opt,name=active_status,json=activeStatus,proto3" json:"active_status,omitempty"`
	Notes          string `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	Sketch         string `protobuf:"bytes,6,opt,name=sketch,proto3" json:"sketch,omitempty"`
	PatientId      string `protobuf:"bytes,7,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	DoctorId       int64  `protobuf:"varint,8,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
}

func (x *PrescriptionResult) Reset() {
	*x = PrescriptionResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prescription_attributes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrescriptionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrescriptionResult) ProtoMessage() {}

func (x *PrescriptionResult) ProtoReflect() protoreflect.Message {
	mi := &file_prescription_attributes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrescriptionResult.ProtoReflect.Descriptor instead.
func (*PrescriptionResult) Descriptor() ([]byte, []int) {
	return file_prescription_attributes_proto_rawDescGZIP(), []int{1}
}

func (x *PrescriptionResult) GetPrescriptionId() int64 {
	if x != nil {
		return x.PrescriptionId
	}
	return 0
}

func (x *PrescriptionResult) GetPresDate() string {
	if x != nil {
		return x.PresDate
	}
	return ""
}

func (x *PrescriptionResult) GetPresTime() string {
	if x != nil {
		return x.PresTime
	}
	return ""
}

func (x *PrescriptionResult) GetActiveStatus() bool {
	if x != nil {
		return x.ActiveStatus
	}
	return false
}

func (x *PrescriptionResult) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *PrescriptionResult) GetSketch() string {
	if x != nil {
		return x.Sketch
	}
	return ""
}

func (x *PrescriptionResult) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *PrescriptionResult) GetDoctorId() int64 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

type LatestPrescriptionResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prescriptions []*PrescriptionResult `protobuf:"bytes,1,rep,name=prescriptions,proto3" json:"prescriptions,omitempty"`
}

func (x *LatestPrescriptionResult) Reset() {
	*x = LatestPrescriptionResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prescription_attributes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LatestPrescriptionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestPrescriptionResult) ProtoMessage() {}

func (x *LatestPrescriptionResult) ProtoReflect() protoreflect.Message {
	mi := &file_prescription_attributes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestPrescriptionResult.ProtoReflect.Descriptor instead.
func (*LatestPrescriptionResult) Descriptor() ([]byte, []int) {
	return file_prescription_attributes_proto_rawDescGZIP(), []int{2}
}

func (x *LatestPrescriptionResult) GetPrescriptions() []*PrescriptionResult {
	if x != nil {
		return x.Prescriptions
	}
	return nil
}

var File_prescription_attributes_proto protoreflect.FileDescriptor

var file_prescription_attributes_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0x40, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74,
	0x50, 0x72, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x74, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x74, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x86, 0x02, 0x0a, 0x12, 0x50, 0x72, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x27, 0x0a, 0x0f,
	0x70, 0x72, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x70, 0x72, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x73, 0x5f, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x65, 0x73, 0x44, 0x61,
	0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x73, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x65, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x23, 0x0a, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6b,
	0x65, 0x74, 0x63, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6b, 0x65, 0x74,
	0x63, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x58,
	0x0a, 0x18, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x50, 0x72, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3c, 0x0a, 0x0d, 0x70, 0x72,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0d, 0x70, 0x72, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_prescription_attributes_proto_rawDescOnce sync.Once
	file_prescription_attributes_proto_rawDescData = file_prescription_attributes_proto_rawDesc
)

func file_prescription_attributes_proto_rawDescGZIP() []byte {
	file_prescription_attributes_proto_rawDescOnce.Do(func() {
		file_prescription_attributes_proto_rawDescData = protoimpl.X.CompressGZIP(file_prescription_attributes_proto_rawDescData)
	})
	return file_prescription_attributes_proto_rawDescData
}

var file_prescription_attributes_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_prescription_attributes_proto_goTypes = []interface{}{
	(*GetLatestPrescriptionsParameters)(nil), // 0: pb.GetLatestPrescriptionsParameters
	(*PrescriptionResult)(nil),               // 1: pb.PrescriptionResult
	(*LatestPrescriptionResult)(nil),         // 2: pb.LatestPrescriptionResult
}
var file_prescription_attributes_proto_depIdxs = []int32{
	1, // 0: pb.LatestPrescriptionResult.prescriptions:type_name -> pb.PrescriptionResult
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_prescription_attributes_proto_init() }
func file_prescription_attributes_proto_init() {
	if File_prescription_attributes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_prescription_attributes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLatestPrescriptionsParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prescription_attributes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrescriptionResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prescription_attributes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LatestPrescriptionResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_prescription_attributes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_prescription_attributes_proto_goTypes,
		DependencyIndexes: file_prescription_attributes_proto_depIdxs,
		MessageInfos:      file_prescription_attributes_proto_msgTypes,
	}.Build()
	File_prescription_attributes_proto = out.File
	file_prescription_attributes_proto_rawDesc = nil
	file_prescription_attributes_proto_goTypes = nil
	file_prescription_attributes_proto_depIdxs = nil
}
