// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: super_admin_attributes.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SuperAdmin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SuperAdminId     int64  `protobuf:"varint,1,opt,name=superAdmin_id,json=superAdminId,proto3" json:"superAdmin_id,omitempty"`
	UserId           string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName         string `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FirstName        string `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName         string `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Nic              string `protobuf:"bytes,6,opt,name=nic,proto3" json:"nic,omitempty"`
	TellNo           string `protobuf:"bytes,7,opt,name=tell_no,json=tellNo,proto3" json:"tell_no,omitempty"`
	Address          string `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	UserEmail        string `protobuf:"bytes,9,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	UserPwd          string `protobuf:"bytes,10,opt,name=user_pwd,json=userPwd,proto3" json:"user_pwd,omitempty"`
	IsEmailVerified  bool   `protobuf:"varint,11,opt,name=is_email_verified,json=isEmailVerified,proto3" json:"is_email_verified,omitempty"`
	IsTellNoVerified bool   `protobuf:"varint,12,opt,name=is_tell_no_verified,json=isTellNoVerified,proto3" json:"is_tell_no_verified,omitempty"`
}

func (x *SuperAdmin) Reset() {
	*x = SuperAdmin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_super_admin_attributes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuperAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuperAdmin) ProtoMessage() {}

func (x *SuperAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_super_admin_attributes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuperAdmin.ProtoReflect.Descriptor instead.
func (*SuperAdmin) Descriptor() ([]byte, []int) {
	return file_super_admin_attributes_proto_rawDescGZIP(), []int{0}
}

func (x *SuperAdmin) GetSuperAdminId() int64 {
	if x != nil {
		return x.SuperAdminId
	}
	return 0
}

func (x *SuperAdmin) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SuperAdmin) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *SuperAdmin) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *SuperAdmin) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *SuperAdmin) GetNic() string {
	if x != nil {
		return x.Nic
	}
	return ""
}

func (x *SuperAdmin) GetTellNo() string {
	if x != nil {
		return x.TellNo
	}
	return ""
}

func (x *SuperAdmin) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SuperAdmin) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *SuperAdmin) GetUserPwd() string {
	if x != nil {
		return x.UserPwd
	}
	return ""
}

func (x *SuperAdmin) GetIsEmailVerified() bool {
	if x != nil {
		return x.IsEmailVerified
	}
	return false
}

func (x *SuperAdmin) GetIsTellNoVerified() bool {
	if x != nil {
		return x.IsTellNoVerified
	}
	return false
}

type RegisterSuperAdminRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId           string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName         string `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FirstName        string `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName         string `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Nic              string `protobuf:"bytes,5,opt,name=nic,proto3" json:"nic,omitempty"`
	TellNo           string `protobuf:"bytes,6,opt,name=tell_no,json=tellNo,proto3" json:"tell_no,omitempty"`
	Address          string `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	UserEmail        string `protobuf:"bytes,8,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	UserPwd          string `protobuf:"bytes,9,opt,name=user_pwd,json=userPwd,proto3" json:"user_pwd,omitempty"`
	IsEmailVerified  bool   `protobuf:"varint,10,opt,name=is_email_verified,json=isEmailVerified,proto3" json:"is_email_verified,omitempty"`
	IsTellNoVerified bool   `protobuf:"varint,11,opt,name=is_tell_no_verified,json=isTellNoVerified,proto3" json:"is_tell_no_verified,omitempty"`
}

func (x *RegisterSuperAdminRequest) Reset() {
	*x = RegisterSuperAdminRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_super_admin_attributes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterSuperAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSuperAdminRequest) ProtoMessage() {}

func (x *RegisterSuperAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_super_admin_attributes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSuperAdminRequest.ProtoReflect.Descriptor instead.
func (*RegisterSuperAdminRequest) Descriptor() ([]byte, []int) {
	return file_super_admin_attributes_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterSuperAdminRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterSuperAdminRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *RegisterSuperAdminRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterSuperAdminRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RegisterSuperAdminRequest) GetNic() string {
	if x != nil {
		return x.Nic
	}
	return ""
}

func (x *RegisterSuperAdminRequest) GetTellNo() string {
	if x != nil {
		return x.TellNo
	}
	return ""
}

func (x *RegisterSuperAdminRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterSuperAdminRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *RegisterSuperAdminRequest) GetUserPwd() string {
	if x != nil {
		return x.UserPwd
	}
	return ""
}

func (x *RegisterSuperAdminRequest) GetIsEmailVerified() bool {
	if x != nil {
		return x.IsEmailVerified
	}
	return false
}

func (x *RegisterSuperAdminRequest) GetIsTellNoVerified() bool {
	if x != nil {
		return x.IsTellNoVerified
	}
	return false
}

type RegisterSuperAdminResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SuperAdminId int64  `protobuf:"varint,1,opt,name=superAdmin_id,json=superAdminId,proto3" json:"superAdmin_id,omitempty"`
	UserId       string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *RegisterSuperAdminResponse) Reset() {
	*x = RegisterSuperAdminResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_super_admin_attributes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterSuperAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSuperAdminResponse) ProtoMessage() {}

func (x *RegisterSuperAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_super_admin_attributes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSuperAdminResponse.ProtoReflect.Descriptor instead.
func (*RegisterSuperAdminResponse) Descriptor() ([]byte, []int) {
	return file_super_admin_attributes_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterSuperAdminResponse) GetSuperAdminId() int64 {
	if x != nil {
		return x.SuperAdminId
	}
	return 0
}

func (x *RegisterSuperAdminResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetSuperAdminsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSuperAdminsRequest) Reset() {
	*x = GetSuperAdminsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_super_admin_attributes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSuperAdminsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSuperAdminsRequest) ProtoMessage() {}

func (x *GetSuperAdminsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_super_admin_attributes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSuperAdminsRequest.ProtoReflect.Descriptor instead.
func (*GetSuperAdminsRequest) Descriptor() ([]byte, []int) {
	return file_super_admin_attributes_proto_rawDescGZIP(), []int{3}
}

type GetSuperAdminsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SuperAdmins []*SuperAdmin `protobuf:"bytes,1,rep,name=superAdmins,proto3" json:"superAdmins,omitempty"`
}

func (x *GetSuperAdminsResponse) Reset() {
	*x = GetSuperAdminsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_super_admin_attributes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSuperAdminsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSuperAdminsResponse) ProtoMessage() {}

func (x *GetSuperAdminsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_super_admin_attributes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSuperAdminsResponse.ProtoReflect.Descriptor instead.
func (*GetSuperAdminsResponse) Descriptor() ([]byte, []int) {
	return file_super_admin_attributes_proto_rawDescGZIP(), []int{4}
}

func (x *GetSuperAdminsResponse) GetSuperAdmins() []*SuperAdmin {
	if x != nil {
		return x.SuperAdmins
	}
	return nil
}

var File_super_admin_attributes_proto protoreflect.FileDescriptor

var file_super_admin_attributes_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x73, 0x75, 0x70, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0xfd, 0x02, 0x0a, 0x0a, 0x53, 0x75, 0x70, 0x65, 0x72, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x75, 0x70, 0x65, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x75, 0x70, 0x65, 0x72, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c,
	0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69, 0x63, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x69, 0x63, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65,
	0x6c, 0x6c, 0x5f, 0x6e, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x6c,
	0x6c, 0x4e, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1d, 0x0a,
	0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x19, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x77, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x50, 0x77, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x69, 0x73, 0x5f, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0f, 0x69, 0x73, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x12, 0x2d, 0x0a, 0x13, 0x69, 0x73, 0x5f, 0x74, 0x65, 0x6c, 0x6c, 0x5f, 0x6e,
	0x6f, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x10, 0x69, 0x73, 0x54, 0x65, 0x6c, 0x6c, 0x4e, 0x6f, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x65, 0x64, 0x22, 0xe7, 0x02, 0x0a, 0x19, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53,
	0x75, 0x70, 0x65, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6e, 0x69, 0x63, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x6c, 0x6c, 0x5f, 0x6e, 0x6f, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x6c, 0x6c, 0x4e, 0x6f, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65,
	0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70,
	0x77, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x50, 0x77,
	0x64, 0x12, 0x2a, 0x0a, 0x11, 0x69, 0x73, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x76, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x69, 0x73,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x2d, 0x0a,
	0x13, 0x69, 0x73, 0x5f, 0x74, 0x65, 0x6c, 0x6c, 0x5f, 0x6e, 0x6f, 0x5f, 0x76, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x69, 0x73, 0x54, 0x65,
	0x6c, 0x6c, 0x4e, 0x6f, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x22, 0x5a, 0x0a, 0x1a,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x75, 0x70, 0x65, 0x72, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x75,
	0x70, 0x65, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0c, 0x73, 0x75, 0x70, 0x65, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53,
	0x75, 0x70, 0x65, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x4a, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x75, 0x70, 0x65, 0x72, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x0b, 0x73,
	0x75, 0x70, 0x65, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x75, 0x70, 0x65, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x52, 0x0b, 0x73, 0x75, 0x70, 0x65, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x73, 0x42, 0x06, 0x5a,
	0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_super_admin_attributes_proto_rawDescOnce sync.Once
	file_super_admin_attributes_proto_rawDescData = file_super_admin_attributes_proto_rawDesc
)

func file_super_admin_attributes_proto_rawDescGZIP() []byte {
	file_super_admin_attributes_proto_rawDescOnce.Do(func() {
		file_super_admin_attributes_proto_rawDescData = protoimpl.X.CompressGZIP(file_super_admin_attributes_proto_rawDescData)
	})
	return file_super_admin_attributes_proto_rawDescData
}

var file_super_admin_attributes_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_super_admin_attributes_proto_goTypes = []interface{}{
	(*SuperAdmin)(nil),                 // 0: pb.SuperAdmin
	(*RegisterSuperAdminRequest)(nil),  // 1: pb.RegisterSuperAdminRequest
	(*RegisterSuperAdminResponse)(nil), // 2: pb.RegisterSuperAdminResponse
	(*GetSuperAdminsRequest)(nil),      // 3: pb.GetSuperAdminsRequest
	(*GetSuperAdminsResponse)(nil),     // 4: pb.GetSuperAdminsResponse
}
var file_super_admin_attributes_proto_depIdxs = []int32{
	0, // 0: pb.GetSuperAdminsResponse.superAdmins:type_name -> pb.SuperAdmin
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_super_admin_attributes_proto_init() }
func file_super_admin_attributes_proto_init() {
	if File_super_admin_attributes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_super_admin_attributes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuperAdmin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_super_admin_attributes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterSuperAdminRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_super_admin_attributes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterSuperAdminResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_super_admin_attributes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSuperAdminsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_super_admin_attributes_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSuperAdminsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_super_admin_attributes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_super_admin_attributes_proto_goTypes,
		DependencyIndexes: file_super_admin_attributes_proto_depIdxs,
		MessageInfos:      file_super_admin_attributes_proto_msgTypes,
	}.Build()
	File_super_admin_attributes_proto = out.File
	file_super_admin_attributes_proto_rawDesc = nil
	file_super_admin_attributes_proto_goTypes = nil
	file_super_admin_attributes_proto_depIdxs = nil
}
