// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: ward_attributes.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WardId       int64  `protobuf:"varint,1,opt,name=ward_id,json=wardId,proto3" json:"ward_id,omitempty"`
	WardType     string `protobuf:"bytes,2,opt,name=ward_type,json=wardType,proto3" json:"ward_type,omitempty"`
	TotOfPatient int64  `protobuf:"varint,3,opt,name=tot_of_patient,json=totOfPatient,proto3" json:"tot_of_patient,omitempty"`
	Period       string `protobuf:"bytes,4,opt,name=period,proto3" json:"period,omitempty"`
	CreatedAt    string `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CenterId     int64  `protobuf:"varint,6,opt,name=center_id,json=centerId,proto3" json:"center_id,omitempty"`
	WardNo       int32  `protobuf:"varint,7,opt,name=ward_no,json=wardNo,proto3" json:"ward_no,omitempty"`
}

func (x *Ward) Reset() {
	*x = Ward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ward_attributes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ward) ProtoMessage() {}

func (x *Ward) ProtoReflect() protoreflect.Message {
	mi := &file_ward_attributes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ward.ProtoReflect.Descriptor instead.
func (*Ward) Descriptor() ([]byte, []int) {
	return file_ward_attributes_proto_rawDescGZIP(), []int{0}
}

func (x *Ward) GetWardId() int64 {
	if x != nil {
		return x.WardId
	}
	return 0
}

func (x *Ward) GetWardType() string {
	if x != nil {
		return x.WardType
	}
	return ""
}

func (x *Ward) GetTotOfPatient() int64 {
	if x != nil {
		return x.TotOfPatient
	}
	return 0
}

func (x *Ward) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *Ward) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Ward) GetCenterId() int64 {
	if x != nil {
		return x.CenterId
	}
	return 0
}

func (x *Ward) GetWardNo() int32 {
	if x != nil {
		return x.WardNo
	}
	return 0
}

type GetWardsByCenterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CenterId int64 `protobuf:"varint,1,opt,name=center_id,json=centerId,proto3" json:"center_id,omitempty"`
}

func (x *GetWardsByCenterRequest) Reset() {
	*x = GetWardsByCenterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ward_attributes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWardsByCenterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWardsByCenterRequest) ProtoMessage() {}

func (x *GetWardsByCenterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ward_attributes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWardsByCenterRequest.ProtoReflect.Descriptor instead.
func (*GetWardsByCenterRequest) Descriptor() ([]byte, []int) {
	return file_ward_attributes_proto_rawDescGZIP(), []int{1}
}

func (x *GetWardsByCenterRequest) GetCenterId() int64 {
	if x != nil {
		return x.CenterId
	}
	return 0
}

type GetWardsByCenterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wards []*Ward `protobuf:"bytes,1,rep,name=wards,proto3" json:"wards,omitempty"`
}

func (x *GetWardsByCenterResponse) Reset() {
	*x = GetWardsByCenterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ward_attributes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWardsByCenterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWardsByCenterResponse) ProtoMessage() {}

func (x *GetWardsByCenterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ward_attributes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWardsByCenterResponse.ProtoReflect.Descriptor instead.
func (*GetWardsByCenterResponse) Descriptor() ([]byte, []int) {
	return file_ward_attributes_proto_rawDescGZIP(), []int{2}
}

func (x *GetWardsByCenterResponse) GetWards() []*Ward {
	if x != nil {
		return x.Wards
	}
	return nil
}

var File_ward_attributes_proto protoreflect.FileDescriptor

var file_ward_attributes_proto_rawDesc = []byte{
	0x0a, 0x15, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xcf, 0x01, 0x0a, 0x04,
	0x57, 0x61, 0x72, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x77, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x77, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x6f,
	0x74, 0x5f, 0x6f, 0x66, 0x5f, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0c, 0x74, 0x6f, 0x74, 0x4f, 0x66, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x6e, 0x6f, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x77, 0x61, 0x72, 0x64, 0x4e, 0x6f, 0x22, 0x36, 0x0a,
	0x17, 0x47, 0x65, 0x74, 0x57, 0x61, 0x72, 0x64, 0x73, 0x42, 0x79, 0x43, 0x65, 0x6e, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x57, 0x61, 0x72, 0x64,
	0x73, 0x42, 0x79, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1e, 0x0a, 0x05, 0x77, 0x61, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x61, 0x72, 0x64, 0x52, 0x05, 0x77, 0x61, 0x72, 0x64,
	0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_ward_attributes_proto_rawDescOnce sync.Once
	file_ward_attributes_proto_rawDescData = file_ward_attributes_proto_rawDesc
)

func file_ward_attributes_proto_rawDescGZIP() []byte {
	file_ward_attributes_proto_rawDescOnce.Do(func() {
		file_ward_attributes_proto_rawDescData = protoimpl.X.CompressGZIP(file_ward_attributes_proto_rawDescData)
	})
	return file_ward_attributes_proto_rawDescData
}

var file_ward_attributes_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ward_attributes_proto_goTypes = []interface{}{
	(*Ward)(nil),                     // 0: pb.Ward
	(*GetWardsByCenterRequest)(nil),  // 1: pb.GetWardsByCenterRequest
	(*GetWardsByCenterResponse)(nil), // 2: pb.GetWardsByCenterResponse
}
var file_ward_attributes_proto_depIdxs = []int32{
	0, // 0: pb.GetWardsByCenterResponse.wards:type_name -> pb.Ward
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ward_attributes_proto_init() }
func file_ward_attributes_proto_init() {
	if File_ward_attributes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ward_attributes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ward_attributes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWardsByCenterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ward_attributes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWardsByCenterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ward_attributes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ward_attributes_proto_goTypes,
		DependencyIndexes: file_ward_attributes_proto_depIdxs,
		MessageInfos:      file_ward_attributes_proto_msgTypes,
	}.Build()
	File_ward_attributes_proto = out.File
	file_ward_attributes_proto_rawDesc = nil
	file_ward_attributes_proto_goTypes = nil
	file_ward_attributes_proto_depIdxs = nil
}
