// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: admitpatient.sql

package db

import (
	"context"
	"time"
)

const admitPatient = `-- name: AdmitPatient :one
INSERT INTO "Patient_Center" ("patient_id", "center_id", "created_at")
VALUES ($1, $2, $3)
RETURNING "patient_id"
`

type AdmitPatientParams struct {
	PatientID string    `json:"patient_id"`
	CenterID  int64     `json:"center_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) AdmitPatient(ctx context.Context, arg AdmitPatientParams) (string, error) {
	row := q.db.QueryRowContext(ctx, admitPatient, arg.PatientID, arg.CenterID, arg.CreatedAt)
	var patient_id string
	err := row.Scan(&patient_id)
	return patient_id, err
}
