// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: center.sql

package db

import (
	"context"
)

const getAllCenterIds = `-- name: GetAllCenterIds :many
SELECT center_id, center_name, address, tell_no, email, website, active_status, online_status, created_at, centertype_id FROM "Center"
ORDER BY "center_id"
`

func (q *Queries) GetAllCenterIds(ctx context.Context) ([]Center, error) {
	rows, err := q.db.QueryContext(ctx, getAllCenterIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Center
	for rows.Next() {
		var i Center
		if err := rows.Scan(
			&i.CenterID,
			&i.CenterName,
			&i.Address,
			&i.TellNo,
			&i.Email,
			&i.Website,
			&i.ActiveStatus,
			&i.OnlineStatus,
			&i.CreatedAt,
			&i.CentertypeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
