// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: drug.sql

package db

import (
	"context"
)

const getDrugById = `-- name: GetDrugById :one
SELECT drug_id, drug_name, scientific_name, drug_category, storage_temperature, dangerous_level, manufacture, no_of_units, notes, created_at FROM "Drug" 
WHERE "drug_id" = $1 
LIMIT 1
`

func (q *Queries) GetDrugById(ctx context.Context, drugID int64) (Drug, error) {
	row := q.db.QueryRowContext(ctx, getDrugById, drugID)
	var i Drug
	err := row.Scan(
		&i.DrugID,
		&i.DrugName,
		&i.ScientificName,
		&i.DrugCategory,
		&i.StorageTemperature,
		&i.DangerousLevel,
		&i.Manufacture,
		&i.NoOfUnits,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
