// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
	"time"
)

type BedTicket struct {
	BedTicketID      int64     `json:"bedTicket_id"`
	BedNo            int32     `json:"bed_no"`
	AssigneddateTime time.Time `json:"assigneddate_time"`
	LeavedateTime    time.Time `json:"leavedate_time"`
	TicketType       string    `json:"ticket_type"`
	CreatedAt        time.Time `json:"created_at"`
	PatientID        string    `json:"patient_id"`
	WardID           int64     `json:"ward_id"`
}

type Center struct {
	CenterID     int64          `json:"center_id"`
	CenterName   string         `json:"center_name"`
	Address      sql.NullString `json:"address"`
	TellNo       string         `json:"tell_no"`
	Email        string         `json:"email"`
	Website      string         `json:"website"`
	ActiveStatus bool           `json:"active_status"`
	OnlineStatus bool           `json:"online_status"`
	CreatedAt    time.Time      `json:"created_at"`
	CentertypeID int64          `json:"centertype_id"`
}

type CenterAdmin struct {
	CenterAdminID int64  `json:"centerAdmin_id"`
	CenterID      int64  `json:"center_id"`
	UserID        string `json:"user_id"`
}

type CenterType struct {
	CentertypeID  int64          `json:"centertype_id"`
	CenterType    string         `json:"center_type"`
	CentertypeDes sql.NullString `json:"centertype_des"`
	CreatedAt     time.Time      `json:"created_at"`
}

type CriticalFacts struct {
	CriticalfactID int64  `json:"criticalfact_id"`
	IllnessID      int64  `json:"illness_id"`
	PatientID      string `json:"patient_id"`
	DoctorID       int64  `json:"doctor_id"`
}

type Doctor struct {
	DoctorID  int64     `json:"doctor_id"`
	RegNumber string    `json:"reg_number"`
	Dob       time.Time `json:"dob"`
	UserID    string    `json:"user_id"`
}

type DoctorCenter struct {
	DoctorID  int64     `json:"doctor_id"`
	CenterID  int64     `json:"center_id"`
	CreatedAt time.Time `json:"created_at"`
}

type DoctorDrugOrder struct {
	DoctorID    int64     `json:"doctor_id"`
	DrugorderID int64     `json:"drugorder_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type Drug struct {
	DrugID             int64          `json:"drug_id"`
	DrugName           string         `json:"drug_name"`
	ScientificName     sql.NullString `json:"scientific_name"`
	DrugCategory       string         `json:"drug_category"`
	StorageTemperature sql.NullString `json:"storage_temperature"`
	DangerousLevel     string         `json:"dangerous_level"`
	Manufacture        string         `json:"manufacture"`
	NoOfUnits          int32          `json:"no_of_units"`
	Notes              sql.NullString `json:"notes"`
	CreatedAt          time.Time      `json:"created_at"`
}

type DrugOrder struct {
	DrugorderID    int64          `json:"drugorder_id"`
	Dose           string         `json:"dose"`
	Dosage         string         `json:"dosage"`
	Givendate      time.Time      `json:"givendate"`
	Giveuntil      time.Time      `json:"giveuntil"`
	Route          string         `json:"route"`
	Frequency      int32          `json:"frequency"`
	DosaageTime    time.Time      `json:"dosaage_time"`
	DrugStatus     sql.NullString `json:"drug_status"`
	DrugID         sql.NullInt64  `json:"drug_id"`
	OmitStatus     int32          `json:"omit_status"`
	PatientID      string         `json:"patient_id"`
	PrescriptionID int64          `json:"prescription_id"`
	SessionID      sql.NullInt64  `json:"session_id"`
	DoctorID       int64          `json:"doctor_id"`
}

type DrugSummery struct {
	DrugsummeryID     int64         `json:"drugsummery_id"`
	SummeryDate       time.Time     `json:"summery_date"`
	SummeryStatus     bool          `json:"summery_status"`
	FirstDoseIsGiven  int32         `json:"first_dose_is_given"`
	SecondDoseIsGiven int32         `json:"second_dose_is_given"`
	ThirdDoseIsGiven  int32         `json:"third_dose_is_given"`
	FourthDoseIsGiven int32         `json:"fourth_dose_is_given"`
	CreatedAt         time.Time     `json:"created_at"`
	DrugorderID       sql.NullInt64 `json:"drugorder_id"`
	PatientID         string        `json:"patient_id"`
}

type Illness struct {
	IllnessID          int64          `json:"illness_id"`
	IllnessName        string         `json:"illness_name"`
	IllnessInformation sql.NullString `json:"illness_information"`
	CreatedAt          time.Time      `json:"created_at"`
}

type Nurse struct {
	NurseID      int64     `json:"nurse_id"`
	RegNumber    string    `json:"reg_number"`
	Dob          time.Time `json:"dob"`
	NurseRank    string    `json:"nurse_rank"`
	ActiveStatus bool      `json:"active_status"`
	CenterID     int64     `json:"center_id"`
	UserID       string    `json:"user_id"`
}

type NurseNotes struct {
	NursingnotesID int64          `json:"nursingnotes_id"`
	Remark         string         `json:"remark"`
	NursingCare    sql.NullString `json:"nursing_care"`
	NotesDatetime  sql.NullTime   `json:"notes_datetime"`
	CreatedAt      time.Time      `json:"created_at"`
	NurseID        int64          `json:"nurse_id"`
	PatientID      string         `json:"patient_id"`
}

type Observation struct {
	ObservationID int64          `json:"observation_id"`
	ObsDatetime   time.Time      `json:"obs_datetime"`
	BpSys         float64        `json:"bp_sys"`
	BpDia         float64        `json:"bp_dia"`
	Pr            float64        `json:"pr"`
	Rr            float64        `json:"rr"`
	Temp          float64        `json:"temp"`
	Notes         sql.NullString `json:"notes"`
	CreatedAt     time.Time      `json:"created_at"`
	PatientID     string         `json:"patient_id"`
	NurseID       int64          `json:"nurse_id"`
}

type PatientCenter struct {
	PatientID string    `json:"patient_id"`
	CenterID  int64     `json:"center_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Prescription struct {
	PrescriptionID int64          `json:"prescription_id"`
	PresDate       time.Time      `json:"pres_date"`
	PresTime       time.Time      `json:"pres_time"`
	ActiveStatus   bool           `json:"active_status"`
	Notes          sql.NullString `json:"notes"`
	Sketch         sql.NullString `json:"sketch"`
	CreatedAt      time.Time      `json:"created_at"`
	PatientID      string         `json:"patient_id"`
	DoctorID       int64          `json:"doctor_id"`
}

type Sessions struct {
	SessionID   int64     `json:"session_id"`
	SessionDate time.Time `json:"session_date"`
	SessionTime time.Time `json:"session_time"`
	CreatedAt   time.Time `json:"created_at"`
	CenterID    int64     `json:"center_id"`
	PatientID   string    `json:"patient_id"`
	DoctorID    int64     `json:"doctor_id"`
}

type Specialization struct {
	SpecializationID   int64     `json:"specialization_id"`
	SpecializationName string    `json:"specialization_name"`
	CreatedAt          time.Time `json:"created_at"`
}

type SpecializationDoctor struct {
	SpecializationID int64     `json:"specialization_id"`
	DoctorID         int64     `json:"doctor_id"`
	CreatedAt        time.Time `json:"created_at"`
}

type SuperAdmin struct {
	SuperAdminID int64  `json:"superAdmin_id"`
	UserID       string `json:"user_id"`
}

type SuperAdminCenter struct {
	SuperadminID int64     `json:"superadmin_id"`
	CenterID     int64     `json:"center_id"`
	CreatedAt    time.Time `json:"created_at"`
}

type TestReport struct {
	TestreportID      int64          `json:"testreport_id"`
	ReportName        string         `json:"report_name"`
	ReportDuration    time.Time      `json:"report_duration"`
	DoctorName        string         `json:"doctor_name"`
	ReportDescription sql.NullString `json:"report_description"`
	Report            string         `json:"report"`
	CreatedAt         time.Time      `json:"created_at"`
	AddedByNurse      bool           `json:"added_by_nurse"`
	TestreporttypeID  int64          `json:"testreporttype_id"`
	PatientID         string         `json:"patient_id"`
	NurseID           sql.NullInt64  `json:"nurse_id"`
}

type TestReportType struct {
	TestreporttypeID int64     `json:"testreporttype_id"`
	TestName         string    `json:"test_name"`
	CreatedAt        time.Time `json:"created_at"`
}

type User struct {
	UserID           string         `json:"user_id"`
	UserName         string         `json:"user_name"`
	FirstName        string         `json:"first_name"`
	LastName         string         `json:"last_name"`
	Nic              string         `json:"nic"`
	TellNo           string         `json:"tell_no"`
	Address          sql.NullString `json:"address"`
	UserEmail        string         `json:"user_email"`
	UserPwd          string         `json:"user_pwd"`
	IsEmailVerified  bool           `json:"is_email_verified"`
	IsTellNoVerified bool           `json:"is_tell_no_verified"`
	CreatedAt        time.Time      `json:"created_at"`
}

type Ward struct {
	WardID       int64     `json:"ward_id"`
	WardNo       int32     `json:"ward_no"`
	TotOfPatient int64     `json:"tot_of_patient"`
	WardType     string    `json:"ward_type"`
	Period       string    `json:"period"`
	CreatedAt    time.Time `json:"created_at"`
	CenterID     int64     `json:"center_id"`
}
