// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: ward.sql

package db

import (
	"context"
)

const getWardsByCenter = `-- name: GetWardsByCenter :many
SELECT ward_id, ward_no, tot_of_patient, ward_type, period, created_at, center_id FROM "Ward"
WHERE "center_id" = $1
ORDER BY "ward_id"
`

func (q *Queries) GetWardsByCenter(ctx context.Context, centerID int64) ([]Ward, error) {
	rows, err := q.db.QueryContext(ctx, getWardsByCenter, centerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ward
	for rows.Next() {
		var i Ward
		if err := rows.Scan(
			&i.WardID,
			&i.WardNo,
			&i.TotOfPatient,
			&i.WardType,
			&i.Period,
			&i.CreatedAt,
			&i.CenterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
